[CmdletBinding(PositionalBinding=$false)]
param(
    [string]$EvidenceRoot = 'docs/hq/tsf_canonical_runtime_app_server_vertical_slice_v1_20260711',
    [switch]$RunLiveReadOnly,
    [switch]$RunLiveWorkspaceWrite
)
$ErrorActionPreference='Stop'
$repo=Split-Path -Parent (Split-Path -Parent $PSCommandPath)
if(![IO.Path]::IsPathRooted($EvidenceRoot)){$EvidenceRoot=Join-Path $repo $EvidenceRoot}
Import-Module (Join-Path $repo 'tools\TsfDurableContract.psm1') -Force
. (Join-Path $repo 'tools\codex-fleet-enforcement-kernel.ps1')
$script:Results=[Collections.Generic.List[object]]::new()
function Assert-Case($Id,$Category,[bool]$Passed,$Observed){$script:Results.Add([pscustomobject]@{case_id=$Id;category=$Category;status=if($Passed){'PASS'}else{'FAIL'};observed=[string]$Observed})|Out-Null;Write-Host "$(if($Passed){'PASS'}else{'FAIL'}) $Id :: $Observed" -ForegroundColor $(if($Passed){'DarkGreen'}else{'Red'})}
function Throws([scriptblock]$Action){try{&$Action|Out-Null;return $false}catch{return $true}}
function Copy-Object($Value){$Value|ConvertTo-Json -Depth 100|ConvertFrom-Json}
function Write-Json($Value,$Path){$parent=Split-Path -Parent $Path;if($parent){New-Item -ItemType Directory -Force $parent|Out-Null};$Value|ConvertTo-Json -Depth 100|Set-Content -LiteralPath $Path -Encoding UTF8}
function Get-Hash($Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}

$runtimeRoot=Join-Path $repo '.codex-local\fixtures\tsf-app-v1'
$fixtureRoot=Get-TsfKernelFullPath (Join-Path $repo '.codex-local\fixtures')
$runtimeFull=Get-TsfKernelFullPath $runtimeRoot
if(!(Test-TsfKernelPathInside $runtimeFull $fixtureRoot)){throw 'Unsafe runtime cleanup path.'}
if(Test-Path $runtimeFull){
    foreach($knownLink in @((Join-Path $runtimeFull 'path-repo\allowed\escape-link'),(Join-Path $runtimeFull 'repo-link'))){if(Test-Path -LiteralPath $knownLink){$item=Get-Item -LiteralPath $knownLink -Force;if(($item.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0){[IO.Directory]::Delete($knownLink,$false)}}}
    Remove-Item -LiteralPath $runtimeFull -Recurse -Force
}
New-Item -ItemType Directory -Force $runtimeFull,$EvidenceRoot|Out-Null

$safeRepo=$repo.Replace('\','/')
$branch=(& git -c "safe.directory=$safeRepo" -C $repo branch --show-current).Trim()
$head=(& git -c "safe.directory=$safeRepo" -C $repo rev-parse HEAD).Trim()
$fingerprint=Get-TsfPolicyFingerprint (Join-Path $repo 'fleet\control\policy-manifest.v1.json') $repo -UnsupportedDevelopmentMode

function New-CanonicalMission {
    param([string]$Id,[string]$Repository,[string]$ExpectedBranch,[string]$StartingHead,[switch]$WorkspaceWrite)
    $created=[datetimeoffset]::UtcNow
    $role=if($WorkspaceWrite){'builder_worker'}else{'auditor_worker'}
    $alias=if($WorkspaceWrite){'BALANCED'}else{'FAST'}
    $route=Resolve-TsfModelRouting $alias CODEX
    $reads=if($WorkspaceWrite){@('input')}else{@('fleet/control/policy-manifest.v1.json')}
    $writes=if($WorkspaceWrite){@('output')}else{@()}
    $artifact=if($WorkspaceWrite){'output/result.txt'}else{'fleet/control/policy-manifest.v1.json'}
    $goal=if($WorkspaceWrite){'Create output/result.txt with exactly: TSF workspace-write round trip complete. Do not modify any other file.'}else{'Return exactly TSF_READ_ONLY_ROUND_TRIP_GREEN. Do not use tools.'}
    [pscustomobject][ordered]@{
        schema_version='tsf_mission_envelope_v1';mission_id=$Id;mission_revision=1;parent_mission_id=$null;project_id='TSF_CONTROL_PLANE';original_request="SYNTHETIC_TSF_CANONICAL_APP_SERVER_ROUND_TRIP_V1 $Id";normalized_goal=$goal;mission_type='canonical_app_server_vertical_slice';worker_role=$role;recommended_surface='CODEX';model_policy_alias=$alias;resolved_model=$route.resolved_model;reasoning_effort=$route.reasoning_effort;model_selection_assurance='RECOMMENDED_ONLY';permission_mode=if($WorkspaceWrite){'WORKSPACE_WRITE'}else{'READ_ONLY'};network_policy='PROHIBITED';control_plane_service_network_policy='CODEX_SERVICE_ONLY';worker_tool_network_policy='DISABLED';repository_allowlist=@($Repository);forbidden_repositories=@();source_allowlist=@();forbidden_sources=@('NORMAL_NWR_PACKETS','SECRETS','CREDENTIALS','PRIVATELENS','PRODUCT_REPOS');branch_worktree_policy=[pscustomobject]@{branch_required=$true;worktree_required=$true;expected_branch=$ExpectedBranch;expected_worktree=$Repository;starting_head=$StartingHead;unexpected_advance_behavior='REJECT'};allowed_reads=@($reads);allowed_writes=@($writes);forbidden_actions=@('push','merge','deploy','install','network','product_repo_mutation','background_runner','persistent_runner','secrets');completion_criteria=@('Bound foreground app-server turn completes and canonical admission succeeds.');required_tests=@([pscustomobject]@{test_id='app-server-automatic-round-trip';required=$true;command='native stable stdio protocol'});required_artifacts=@([pscustomobject]@{path=$artifact;hash_required=$true});required_verifier_independence='SEPARATE_ROLE';stop_conditions=@('Unexpected file touch.','Worker tool network request.','Native identity mismatch.','Timeout.','Verifier failure.');approval_references=@();policy=[pscustomobject]@{policy_commit=$fingerprint.policy_commit;manifest_version='tsf_policy_manifest_v1';fingerprint=$fingerprint.fingerprint;mission_schema_version='tsf_mission_envelope_v1';expected_result_schema_version='tsf_result_envelope_v1'};created_at=$created.ToString('o');expires_at=$created.AddMinutes(45).ToString('o');stale_state_behavior='TIM_REQUIRED';required_result_envelope_version='tsf_result_envelope_v1'
    }
}

$readMission=New-CanonicalMission 'synthetic-tsf-readonly-appserver-0001' $repo $branch $head
Assert-Case 'VS-SCHEMA-001' schema (Test-TsfMissionEnvelope $readMission).valid 'read-only durable mission schema'
$readQueue=ConvertTo-TsfCanonicalExecutionArtifacts $readMission $repo
$readQueue2=ConvertTo-TsfCanonicalExecutionArtifacts $readMission $repo
Assert-Case 'VS-QUEUE-001' queue ((Get-TsfContractJsonHash $readQueue)-eq(Get-TsfContractJsonHash $readQueue2)) 'deterministic queue document'
$readQueueCheck=Test-TsfCanonicalQueueDocument $readQueue $readMission $repo
Assert-Case 'VS-QUEUE-002' queue $readQueueCheck.valid ($readQueueCheck.errors -join '; ')
Assert-Case 'VS-QUEUE-003' queue ($readQueue.source_binding.durable_mission_id-eq$readMission.mission_id-and$readQueue.source_binding.durable_mission_revision-eq1-and$readQueue.source_binding.policy_fingerprint-eq$fingerprint.fingerprint) 'durable binding preserved'
$swapped=Copy-Object $readQueue;$swapped.mission_packet.mission_id='unrelated-mission';Assert-Case 'VS-QUEUE-004' queue (!(Test-TsfCanonicalQueueDocument $swapped $readMission $repo -SkipRuntimeObservation).valid) 'swapped queue record rejected'
$roleSpoof=Copy-Object $readQueue;$roleSpoof.role_extension.worker_role='builder_worker';Assert-Case 'VS-QUEUE-005' queue (!(Test-TsfCanonicalQueueDocument $roleSpoof $readMission $repo -SkipRuntimeObservation).valid) 'role-extension spoof rejected'
$effortConflict=Copy-Object $readMission;$effortConflict.reasoning_effort='HIGH';Assert-Case 'VS-MODEL-001' model (Throws {ConvertTo-TsfCanonicalExecutionArtifacts $effortConflict $repo}) 'model-effort conflict fails closed'

Assert-Case 'VS-EFFORT-001' effort ((ConvertTo-TsfCanonicalEffortName 'LIGHT')-eq'LIGHT'-and(ConvertTo-TsfCanonicalEffortName 'low')-eq'LIGHT'-and(ConvertTo-TsfCanonicalEffortName 'LOW')-eq'LIGHT') 'LIGHT/low/LOW normalize canonically'
$baseEffortAdapter=[pscustomobject][ordered]@{mission_requested_effort='LIGHT';canonical_resolved_effort='LIGHT';thread_default_effort='low';turn_requested_effort='low';effective_effort='UNKNOWN';effective_effort_raw=$null;effective_effort_source='NOT_EXPOSED';effort_assurance='RECOMMENDED_ONLY';required_effort_assurance='RECOMMENDED_ONLY';turn_request_acknowledged=$true;native_reroute_or_override_events=@()}
$matchingEffort=Get-TsfEffortEvidence $readMission $baseEffortAdapter;Assert-Case 'VS-EFFORT-002' effort (@($matchingEffort.effort_conflicts).Count-eq0-and$matchingEffort.turn_requested_effort-eq'low') 'matching thread default and turn request'
$differentDefault=Copy-Object $baseEffortAdapter;$differentDefault.thread_default_effort='high';$differentEvidence=Get-TsfEffortEvidence $readMission $differentDefault;Assert-Case 'VS-EFFORT-003' effort (@($differentEvidence.effort_conflicts)-contains'THREAD_DEFAULT_DIFFERS_FROM_TURN_REQUEST') 'thread default differs without becoming effective proof'
Assert-Case 'VS-EFFORT-004' effort ($differentEvidence.effective_effort-eq'UNKNOWN'-and$differentEvidence.effective_effort_source-eq'NOT_EXPOSED') 'effective effort unavailable remains unknown'
$effectiveMatch=Copy-Object $baseEffortAdapter;$effectiveMatch.effective_effort='LIGHT';$effectiveMatch.effective_effort_raw='low';$effectiveMatch.effective_effort_source='THREAD_SETTINGS_UPDATED';$effectiveMatch.effort_assurance='ADAPTER_VERIFIED';$effectiveMatchEvidence=Get-TsfEffortEvidence $readMission $effectiveMatch;Assert-Case 'VS-EFFORT-005' effort ($effectiveMatchEvidence.effective_effort-eq'LIGHT'-and$effectiveMatchEvidence.effort_admission_effect-eq'ADMITTED') 'authoritative effective effort matches'
$effectiveMismatch=Copy-Object $effectiveMatch;$effectiveMismatch.effective_effort='HIGH';$effectiveMismatch.effective_effort_raw='high';$effectiveMismatchEvidence=Get-TsfEffortEvidence $readMission $effectiveMismatch;Assert-Case 'VS-EFFORT-006' effort ($effectiveMismatchEvidence.effort_admission_effect-eq'REJECTED_OUT_OF_SCOPE') 'authoritative effective effort mismatch fails closed'
$reroute=Copy-Object $baseEffortAdapter;$reroute.native_reroute_or_override_events=@([pscustomobject]@{method='model/rerouted';sequence=9;thread_id='fake-thread';turn_id='fake-turn';raw_payload_json='{"threadId":"fake-thread","turnId":"fake-turn"}';raw_payload_sha256=('a'*64)});$rerouteEvidence=Get-TsfEffortEvidence $readMission $reroute;Assert-Case 'VS-EFFORT-007' effort (@($rerouteEvidence.native_reroute_or_override_events).Count-eq1-and@($rerouteEvidence.effort_conflicts)-contains'NATIVE_MODEL_REROUTE_OBSERVED') 'native reroute preserved and evaluated'
Assert-Case 'VS-EFFORT-008' effort ($differentEvidence.effort_admission_effect-eq'ADMITTED_WITH_CAVEATS'-and$differentEvidence.effort_assurance-eq'RECOMMENDED_ONLY') 'RECOMMENDED_ONLY unknown effective effort admits with caveats'
$adapterRequiredMission=Copy-Object $readMission;$adapterRequiredMission.model_selection_assurance='ADAPTER_VERIFIED';$adapterRequired=Copy-Object $baseEffortAdapter;$adapterRequired.required_effort_assurance='ADAPTER_VERIFIED';$adapterRequiredEvidence=Get-TsfEffortEvidence $adapterRequiredMission $adapterRequired;Assert-Case 'VS-EFFORT-009' effort ($adapterRequiredEvidence.effort_admission_effect-eq'TIM_REQUIRED') 'ADAPTER_VERIFIED mission rejects unknown effective effort'
$exactMismatch=Copy-Object $effectiveMismatch;$exactMismatch.required_effort_assurance='ADAPTER_VERIFIED';$exactMismatchEvidence=Get-TsfEffortEvidence $adapterRequiredMission $exactMismatch;Assert-Case 'VS-EFFORT-010' effort ($exactMismatchEvidence.effort_admission_effect-eq'REJECTED_OUT_OF_SCOPE') 'exact-effort mission rejects authoritative mismatch'
$callerSpoof=Copy-Object $baseEffortAdapter;$callerSpoof|Add-Member caller_supplied_effective_effort 'HIGH';$callerSpoofEvidence=Get-TsfEffortEvidence $readMission $callerSpoof;Assert-Case 'VS-EFFORT-011' effort ($callerSpoofEvidence.effective_effort-eq'UNKNOWN') 'unbound caller effort cannot become observed evidence'
$rawCase=Copy-Object $baseEffortAdapter;$rawCase.thread_default_effort='HiGh';$rawCase.turn_requested_effort='low';$rawCaseEvidence=Get-TsfEffortEvidence $readMission $rawCase;Assert-Case 'VS-EFFORT-012' effort ($rawCaseEvidence.thread_default_effort-ceq'HiGh'-and$rawCaseEvidence.turn_requested_effort-ceq'low') 'raw native effort values preserved unchanged'

$pathRepo=Join-Path $runtimeRoot 'path-repo';New-Item -ItemType Directory -Force (Join-Path $pathRepo 'allowed'),(Join-Path $runtimeRoot 'outside')|Out-Null;Set-Content -LiteralPath (Join-Path $pathRepo 'allowed\file.txt') -Value 'x';Set-Content -LiteralPath (Join-Path $runtimeRoot 'outside\escape.txt') -Value 'escape'
Assert-Case 'VS-PATH-001' path (Test-TsfKernelPathContained 'allowed/file.txt' $pathRepo @('allowed/file.txt')) 'exact path equality'
Assert-Case 'VS-PATH-002' path (Test-TsfKernelPathContained 'allowed\file.txt' $pathRepo @('allowed')) 'separator descendant'
Assert-Case 'VS-PATH-003' path (!(Test-TsfKernelPathContained 'allowed-sibling/file.txt' $pathRepo @('allowed'))) 'sibling prefix rejected'
Assert-Case 'VS-PATH-004' path (!(Test-TsfKernelPathContained 'allowed/../outside.txt' $pathRepo @('allowed'))) 'traversal rejected'
Assert-Case 'VS-PATH-005' path (!(Test-TsfKernelPathContained (Join-Path $pathRepo 'allowed\file.txt') $pathRepo @('allowed'))) 'rooted injection rejected'
$junction=Join-Path $pathRepo 'allowed\escape-link';$junctionMade=$false;try{New-Item -ItemType Junction -Path $junction -Target (Join-Path $runtimeRoot 'outside')|Out-Null;$junctionMade=$true}catch{}
Assert-Case 'VS-PATH-006' path ($junctionMade-and!(Test-TsfKernelPathContained 'allowed/escape-link/escape.txt' $pathRepo @('allowed'))) 'detectable reparse escape rejected'
$repoLink=Join-Path $runtimeRoot 'repo-link';$rootLinkMade=$false;try{New-Item -ItemType Junction -Path $repoLink -Target $pathRepo|Out-Null;$rootLinkMade=$true}catch{}
$rootRejected=$false;if($rootLinkMade){$probe=". '$($repo.Replace("'","''"))\tools\codex-fleet-enforcement-kernel.ps1'; if(!(Test-TsfKernelPathContained 'allowed/file.txt' '$($repoLink.Replace("'","''"))' @('allowed'))){exit 0}else{exit 1}";& powershell -NoProfile -ExecutionPolicy Bypass -Command $probe|Out-Null;$rootRejected=$LASTEXITCODE-eq0;[IO.Directory]::Delete($repoLink,$false)}
Assert-Case 'VS-PATH-007' path ($rootLinkMade-and$rootRejected) 'reparse repository root rejected'

$approvalSchema=Join-Path $repo 'docs\hq\enforcement_kernel\minimum_viable_local_tsf_enforcement_kernel_v1\approval_ledger_schema_v1.json'
$invalidLedger=[pscustomobject]@{schema_version=1;ledger_id='invalid-anyof';approvals=@([pscustomobject]@{approval_id='approval-1';approved_by='fixture';approved_at='2026-07-10T00:00:00Z';repo_path=$repo;lane='MASTER_TSF_CONTROL_PLANE';exact_action='local_write';allowed_files_or_paths=@('fleet/control');required_verifier='verifier_worker';notes='missing expires and scope'})}
Assert-Case 'VS-APPROVAL-001' approval (!(Test-TsfJsonContract $invalidLedger $approvalSchema).valid) 'approval anyOf enforced'
$validLedger=Copy-Object $invalidLedger;$validLedger.approvals[0]|Add-Member expires_at '2099-01-01T00:00:00Z';Assert-Case 'VS-APPROVAL-002' approval (Test-TsfJsonContract $validLedger $approvalSchema).valid 'approval anyOf valid branch'
$approvalMission=Copy-Object $readQueue.mission_packet;$approvalMission.approval_requirements=@([pscustomobject]@{approval_id='approval-1';exact_action='local_write';required=$true;reason='test'});$match=Find-TsfKernelApprovalMatches $approvalMission $validLedger '' -CurrentTime ([datetimeoffset]'2026-07-10T12:00:00Z') -RequireCanonicalUsageBinding;Assert-Case 'VS-APPROVAL-003' approval (!$match[0].satisfied) $match[0].match_status
$canonicalApproval=Copy-Object $validLedger.approvals[0];$canonicalApproval|Add-Member state 'ACTIVE';$canonicalApproval|Add-Member mission_id $readMission.mission_id;$canonicalApproval|Add-Member usage_count 0;$canonicalApproval|Add-Member max_uses 2;$canonicalApproval|Add-Member reuse_policy 'SINGLE_USE';$canonicalApproval|Add-Member worktree_path $repo;$reuseLedger=[pscustomobject]@{schema_version=1;ledger_id='reuse';approvals=@($canonicalApproval)};$reuseMatch=Find-TsfKernelApprovalMatches $approvalMission $reuseLedger '' -CurrentTime ([datetimeoffset]'2026-07-10T12:00:00Z') -RequireCanonicalUsageBinding;Assert-Case 'VS-APPROVAL-004' approval (!$reuseMatch[0].satisfied-and$reuseMatch[0].match_status-eq'MATCH_REUSE_POLICY_INVALID') $reuseMatch[0].match_status
$stale=Copy-Object $canonicalApproval;$stale.max_uses=1;$stale.expires_at='2020-01-01T00:00:00Z';$staleLedger=[pscustomobject]@{schema_version=1;ledger_id='stale';approvals=@($stale)};$staleMatch=Find-TsfKernelApprovalMatches $approvalMission $staleLedger '' -CurrentTime ([datetimeoffset]'2026-07-10T12:00:00Z') -RequireCanonicalUsageBinding;Assert-Case 'VS-APPROVAL-005' approval (!$staleMatch[0].satisfied) $staleMatch[0].match_status
$fixtureApproval=Copy-Object $canonicalApproval;$fixtureApproval.max_uses=1;$fixtureApproval|Add-Member sample_fixture_only $true;$fixtureLedger=[pscustomobject]@{schema_version=1;ledger_id='fixture-leak';approvals=@($fixtureApproval)};$fixtureLedgerPath=Join-Path $runtimeRoot 'fixture-ledger.json';Write-Json $fixtureLedger $fixtureLedgerPath;$fixtureMatch=Find-TsfKernelApprovalMatches $approvalMission $fixtureLedger $fixtureLedgerPath -CurrentTime ([datetimeoffset]'2026-07-10T12:00:00Z') -RequireCanonicalUsageBinding;Assert-Case 'VS-APPROVAL-006' approval (!$fixtureMatch[0].satisfied-and$fixtureMatch[0].match_status-eq'FIXTURE_MATCH_NOT_AUTHORITY') $fixtureMatch[0].match_status
Assert-Case 'VS-REPLAY-001' replay (!(Get-Command Get-TsfAdmissionDecision).Parameters.ContainsKey('PreservationPacketPath')) 'receipt root is not caller-selectable'

$fingerprintRepo=Join-Path $env:TEMP 'tsf-fp-vslice';if(Test-Path $fingerprintRepo){Remove-Item -LiteralPath $fingerprintRepo -Recurse -Force};New-Item -ItemType Directory -Force $fingerprintRepo|Out-Null;$manifest=Get-Content (Join-Path $repo 'fleet\control\policy-manifest.v1.json') -Raw|ConvertFrom-Json
foreach($rel in @('fleet/control/policy-manifest.v1.json')+@($manifest.governing_files)){$src=Join-Path $repo $rel;$dst=Join-Path $fingerprintRepo $rel;New-Item -ItemType Directory -Force (Split-Path -Parent $dst)|Out-Null;Copy-Item -LiteralPath $src -Destination $dst}
& git -C $fingerprintRepo init -q;& git -C $fingerprintRepo config user.email 'fixture@tsf.invalid';& git -C $fingerprintRepo config user.name 'TSF Fixture';& git -C $fingerprintRepo add .;& git -C $fingerprintRepo commit -q -m fixture
$fpBase=Get-TsfPolicyFingerprint (Join-Path $fingerprintRepo 'fleet\control\policy-manifest.v1.json') $fingerprintRepo
Set-Content -LiteralPath (Join-Path $fingerprintRepo 'unrelated.txt') -Value 'unrelated';$fpUnrelated=Get-TsfPolicyFingerprint (Join-Path $fingerprintRepo 'fleet\control\policy-manifest.v1.json') $fingerprintRepo;Assert-Case 'VS-FP-001' fingerprint ($fpBase.fingerprint-eq$fpUnrelated.fingerprint) 'unrelated file excluded'
$governingClasses=@('tools/TsfDurableContract.Canonical.ps1','tools/Invoke-TsfMissionQueueForegroundExecutor.ps1','tools/Test-TsfWorkerRolePermission.ps1','docs/hq/enforcement_kernel/minimum_viable_local_tsf_enforcement_kernel_v1/approval_ledger_schema_v1.json','fleet/control/result-envelope.schema.v1.json')
$fpIndex=1;foreach($rel in $governingClasses){Add-Content -LiteralPath (Join-Path $fingerprintRepo $rel) -Value ' ';$changed=Get-TsfPolicyFingerprint (Join-Path $fingerprintRepo 'fleet\control\policy-manifest.v1.json') $fingerprintRepo -UnsupportedDevelopmentMode;Assert-Case ("VS-FP-{0:d3}"-f($fpIndex+1)) fingerprint ($changed.fingerprint-ne$fpBase.fingerprint) $rel;& git -C $fingerprintRepo checkout -q -- $rel;$fpIndex++}

$fakeCwd=Join-Path $runtimeRoot 'fake-cwd';New-Item -ItemType Directory -Force $fakeCwd|Out-Null;$promptPath=Join-Path $runtimeRoot 'fake-prompt.txt';Set-Content -LiteralPath $promptPath -Value 'Return exactly TSF_FAKE_GREEN.'
function Invoke-FakeAdapter {
    param(
        [string]$Mode,
        [string]$MissionId='fake-mission-0001',
        [int]$MissionRevision=1,
        [string]$PolicyFingerprint=('a'*64),
        [string]$QueueDocumentSha256=('b'*64),
        [string]$Cwd=$fakeCwd,
        [string]$RequiredEffortAssurance='RECOMMENDED_ONLY'
    )
    $safeId=$MissionId-replace'[^A-Za-z0-9._-]','_';$out=Join-Path $runtimeRoot "fake-$Mode-$safeId";New-Item -ItemType Directory -Force $out|Out-Null
    $old=$env:TSF_FAKE_APP_SERVER_MODE;$env:TSF_FAKE_APP_SERVER_MODE=$Mode
    try{
        $resultPath=Join-Path $out 'ar.json';$eventPath=Join-Path $out 'ej.jsonl';$stderrPath=Join-Path $out 'se.log'
        & node (Join-Path $repo 'tools\tsf-codex-app-server-adapter.mjs') --codex-executable (Join-Path $repo 'tests\fixtures\fleet\durable-contract\fake-codex-app-server.mjs') --mission-id $MissionId --mission-revision $MissionRevision --policy-fingerprint $PolicyFingerprint --queue-document-sha256 $QueueDocumentSha256 --cwd $Cwd --model 'gpt-5.6-luna' --mission-requested-effort 'LIGHT' --canonical-resolved-effort 'LIGHT' --required-effort-assurance $RequiredEffortAssurance --effort 'low' --sandbox 'read-only' --prompt-file $promptPath --output-dir $out --result-file $resultPath --event-file $eventPath --stderr-file $stderrPath --timeout-seconds 2 --expires-at '2099-01-01T00:00:00Z'|Out-Null
        $exit=$LASTEXITCODE;$result=Get-Content $resultPath -Raw|ConvertFrom-Json
        return [pscustomobject]@{exit=$exit;result=$result;out=$out;result_path=$resultPath}
    }finally{$env:TSF_FAKE_APP_SERVER_MODE=$old}
}
$fakeNormal=Invoke-FakeAdapter normal;Assert-Case 'VS-PROTOCOL-001' protocol ($fakeNormal.exit-eq0-and$fakeNormal.result.success) 'stable fake protocol'
$fakeEffortMatch=Invoke-FakeAdapter 'effort-match';Assert-Case 'VS-PROTOCOL-EFFORT-001' protocol ($fakeEffortMatch.exit-eq0-and$fakeEffortMatch.result.thread_default_effort-eq'low'-and$fakeEffortMatch.result.turn_requested_effort-eq'low'-and$fakeEffortMatch.result.effective_effort-eq'LIGHT'-and$fakeEffortMatch.result.effective_effort_source-eq'THREAD_SETTINGS_UPDATED') 'native settings update binds matching effective effort'
$fakeEffortMismatch=Invoke-FakeAdapter 'effort-mismatch';Assert-Case 'VS-PROTOCOL-EFFORT-002' protocol ($fakeEffortMismatch.exit-eq0-and$fakeEffortMismatch.result.thread_default_effort-eq'high'-and$fakeEffortMismatch.result.turn_requested_effort-eq'low'-and$fakeEffortMismatch.result.effective_effort-eq'HIGH'-and@($fakeEffortMismatch.result.effort_conflicts)-contains'EFFECTIVE_EFFORT_DIFFERS_FROM_CANONICAL_RESOLUTION') 'native settings update preserves effective mismatch'
$fakeReroute=Invoke-FakeAdapter reroute;Assert-Case 'VS-PROTOCOL-EFFORT-003' protocol ($fakeReroute.exit-eq0-and@($fakeReroute.result.native_reroute_or_override_events|Where-Object method -eq 'model/rerouted').Count-eq1) 'native reroute event preserved'
$fakeUsage=Invoke-FakeAdapter normal;Assert-Case 'VS-USAGE-001' usage ($fakeUsage.exit-eq0-and$fakeUsage.result.turn_usage.evidence_classification-eq'NATIVE_OBSERVED'-and$fakeUsage.result.turn_usage.total_tokens-eq10-and$fakeUsage.result.turn_usage.raw_payload_sha256) 'one bound native usage event'
$fakeUsageMultiple=Invoke-FakeAdapter 'usage-multiple';Assert-Case 'VS-USAGE-002' usage ($fakeUsageMultiple.exit-eq0-and$fakeUsageMultiple.result.turn_usage.event_count-eq2-and$fakeUsageMultiple.result.turn_usage.unique_event_count-eq2-and$fakeUsageMultiple.result.turn_usage.total_tokens-eq20) 'multiple increasing usage updates select greatest cumulative snapshot'
$fakeUsageDuplicate=Invoke-FakeAdapter 'usage-duplicate';Assert-Case 'VS-USAGE-003' usage ($fakeUsageDuplicate.exit-eq0-and$fakeUsageDuplicate.result.turn_usage.event_count-eq2-and$fakeUsageDuplicate.result.turn_usage.unique_event_count-eq1-and$fakeUsageDuplicate.result.turn_usage.total_tokens-eq10) 'duplicate usage retained but not promoted twice'
$fakeUsageOutOfOrder=Invoke-FakeAdapter 'usage-out-of-order';Assert-Case 'VS-USAGE-004' usage ($fakeUsageOutOfOrder.exit-eq0-and$fakeUsageOutOfOrder.result.turn_usage.total_tokens-eq20) 'out-of-order usage selects greatest cumulative snapshot'
$fakeUsageAbsent=Invoke-FakeAdapter 'usage-absent';Assert-Case 'VS-USAGE-005' usage ($fakeUsageAbsent.exit-eq0-and$fakeUsageAbsent.result.turn_usage.status-eq'NOT_EXPOSED'-and$fakeUsageAbsent.result.turn_usage.evidence_classification-eq'UNVERIFIED'-and$null-eq$fakeUsageAbsent.result.turn_usage.total_tokens) 'absent usage remains unknown'
$fakeUsageMismatch=Invoke-FakeAdapter 'usage-mismatch';Assert-Case 'VS-USAGE-006' usage ($fakeUsageMismatch.exit-ne0-and$fakeUsageMismatch.result.failure-match'Spoofed turn id') $fakeUsageMismatch.result.failure
$fakeUsageMalformed=Invoke-FakeAdapter 'usage-malformed';Assert-Case 'VS-USAGE-007' usage ($fakeUsageMalformed.exit-ne0-and$fakeUsageMalformed.result.failure-match'Malformed native token usage') $fakeUsageMalformed.result.failure
foreach($mode in @('malformed','exit','timeout','duplicate','out-of-order','spoof')){$fake=Invoke-FakeAdapter $mode;Assert-Case ("VS-PROTOCOL-$mode") protocol ($fake.exit-ne0-and!$fake.result.success) $fake.result.failure}

$mapperRoot=Join-Path $runtimeRoot 'mapper-producer-binding';New-Item -ItemType Directory -Force $mapperRoot|Out-Null
$mapperQueuePath=Join-Path $mapperRoot 'queue.json';Write-Json $readQueue $mapperQueuePath
$mapperQueueHash=Get-TsfContractJsonHash $readQueue
$mapperAdapter=Invoke-FakeAdapter normal $readMission.mission_id $readMission.mission_revision $readMission.policy.fingerprint $mapperQueueHash $repo $readMission.model_selection_assurance
$mapperPreflightPath=Join-Path $mapperRoot 'preflight.json';Write-Json ([pscustomobject]@{mission_id=$readMission.mission_id;preflight_approved=$true}) $mapperPreflightPath
$mapperRolePath=Join-Path $mapperRoot 'role.json';Write-Json ([pscustomobject]@{role_id=$readMission.worker_role;role_preflight_approved=$true}) $mapperRolePath
$mapperWorkerPath=Join-Path $mapperRoot 'worker.json';Write-Json ([pscustomobject]@{mission_id=$readMission.mission_id;files_touched=@();tests=@([pscustomobject]@{test_id='app-server-automatic-round-trip';status='PASS';observed='bound fake adapter';evidence=$mapperAdapter.result.event_journal_sha256});approval_use=@()}) $mapperWorkerPath
$mapperVerifierPath=Join-Path $mapperRoot 'verifier.json';Write-Json ([pscustomobject]@{mission_id=$readMission.mission_id;verified=$true}) $mapperVerifierPath
$mapperPreservationPath=Join-Path $mapperRoot 'preservation\packet\preservation_packet.json';Write-Json ([pscustomobject]@{mission_id=$readMission.mission_id;final_decision='GREEN'}) $mapperPreservationPath
$mapperRuntime=[pscustomobject][ordered]@{schema_version='tsf_authenticated_runtime_evidence_v1';result_id='mapper-caller-spoof-result-0001';queue_document_path=$mapperQueuePath;adapter_result_path=$mapperAdapter.result_path;preflight_path=$mapperPreflightPath;role_preflight_path=$mapperRolePath;worker_result_path=$mapperWorkerPath;verifier_result_path=$mapperVerifierPath;preservation_packet_path=$mapperPreservationPath;starting_head=$head;base_head=$head;dirty_before=$true;effective_effort='HIGH';effective_effort_source='CALLER_REPORTED';proposed_next_action='Verify caller effort cannot become authority.';created_at=[datetimeoffset]::UtcNow.ToString('o')}
$mapperResult=ConvertTo-TsfDurableResultEnvelope $readMission $mapperRuntime $repo
Assert-Case 'VS-EFFORT-013' effort ($mapperResult.actual_reasoning_effort-eq'UNKNOWN'-and$mapperResult.effort_evidence.effective_effort_source-eq'NOT_EXPOSED'-and$mapperResult.evidence_bindings.effort-eq'UNVERIFIED') 'caller RuntimeEvidence effort cannot be promoted by mapper'
Assert-Case 'VS-USAGE-008' usage ($mapperResult.usage_evidence.evidence_classification-eq'NATIVE_OBSERVED'-and$mapperResult.usage_evidence.total_tokens-eq10-and$mapperResult.evidence_bindings.usage-eq'NATIVE_OBSERVED') 'mapper retains only journal-bound native usage'

$compactRoot=Join-Path $repo '.codex-local\rt-test';if(Test-Path -LiteralPath $compactRoot){if(!(Test-TsfKernelPathInside $compactRoot (Join-Path $repo '.codex-local'))){throw 'Unsafe compact test cleanup root.'};Remove-Item -LiteralPath $compactRoot -Recurse -Force}
$longStorageMission='mission-'+('m'*500);$longStorageRun='result-'+('r'*500);$longPlan=New-TsfRuntimeStoragePlan $compactRoot $longStorageMission 99 $longStorageRun
$longPlan2=New-TsfRuntimeStoragePlan $compactRoot $longStorageMission 99 $longStorageRun
Assert-Case 'VS-STORAGE-001' storage ($longPlan.mission_identity.short_key-eq$longPlan2.mission_identity.short_key-and$longPlan.run_identity.short_key-eq$longPlan2.run_identity.short_key) 'long mission/result identities map deterministically'
Assert-Case 'VS-STORAGE-002' storage ($longPlan.mission_identity.short_key-match'^[a-z2-7]{32}$'-and$longPlan.run_identity.short_key-match'^[a-z2-7]{32}$'-and$longPlan.mission_identity.effective_security_bits-eq160) 'fixed Base32 keys retain 160 digest bits'
Assert-Case 'VS-STORAGE-003' storage ($longPlan.directory-notmatch[regex]::Escape($longStorageMission)-and$longPlan.directory-notmatch[regex]::Escape($longStorageRun)) 'raw logical identifiers never enter runtime paths'
Assert-Case 'VS-STORAGE-004' storage ($longPlan.budget.valid-and$longPlan.budget.maximum_path_length-le225) "all planned paths fit hard/target budgets; max $($longPlan.budget.maximum_path_length)"
$catalog=Get-TsfRuntimeArtifactCatalog;Assert-Case 'VS-STORAGE-005' storage ($catalog.manifest-eq'manifest.json'-and$catalog.mission-eq'm.json'-and$catalog.worker_result-eq'wr.json'-and$catalog.preservation_packet-eq'pp.json'-and$catalog.durable_result-eq'dr.json'-and$catalog.event_journal-eq'ej.jsonl') 'fixed compact artifact catalog'

$compactInputRoot=Join-Path $runtimeRoot 'compact-input';New-Item -ItemType Directory -Force $compactInputRoot|Out-Null
$compactMissionPath=Join-Path $compactInputRoot 'm.json';Write-Json $readQueueCheck.effective_mission $compactMissionPath
$compactPreflight=Join-Path $compactInputRoot 'pf.json';Write-Json ([pscustomobject]@{mission_id=$readMission.mission_id;verdict='GREEN';preflight_approved=$true}) $compactPreflight
$compactRole=Join-Path $compactInputRoot 'rp.json';Write-Json ([pscustomobject]@{mission_id=$readMission.mission_id;role_id=$readMission.worker_role;role_preflight_approved=$true}) $compactRole
$compactInstruction=Join-Path $compactInputRoot 'wi.json';Write-Json $readQueue.worker_instruction_packet $compactInstruction
$compactWorker=Join-Path $compactInputRoot 'wr.json';Write-Json ([pscustomobject]@{mission_id=$readMission.mission_id;files_touched=@();tests=@();approval_use=@()}) $compactWorker
$compactVerifier=Join-Path $compactInputRoot 'vr.json';Write-Json ([pscustomobject]@{mission_id=$readMission.mission_id;verdict='GREEN';verified=$true}) $compactVerifier
$compactRunId=$mapperRuntime.result_id
$compactPacket=Write-TsfKernelPreservationPacket -MissionPath $compactMissionPath -PreflightResultPath $compactPreflight -RolePreflightPath $compactRole -WorkerInstructionPath $compactInstruction -WorkerResultPath $compactWorker -VerifierResultPath $compactVerifier -AdapterResultPath $mapperAdapter.result_path -EventJournalPath $mapperAdapter.result.event_journal_path -OutputDirectory $compactRoot -RunId $compactRunId -DurableMission $readMission
$compactManifest=Get-Content $compactPacket.manifest_path -Raw|ConvertFrom-Json;$compactManifestCheck=Test-TsfRuntimeStorageManifest $compactManifest $compactPacket.packet_directory $readMission.mission_id $readMission.mission_revision $compactRunId
Assert-Case 'VS-STORAGE-006' storage ($compactManifestCheck.valid-and$compactManifest.mission_identity_sha256.Length-eq64-and$compactManifest.run_identity_sha256.Length-eq64) 'complete compact manifest validates full SHA-256 identities'
Assert-Case 'VS-STORAGE-007' storage (@($compactManifest.artifacts|Where-Object{!(Test-Path -LiteralPath (Join-Path $compactPacket.packet_directory $_.path))}).Count-eq0) 'manifest binds every compact artifact to observed bytes'
$manifestMismatch=Copy-Object $compactManifest;$manifestMismatch.mission_identity_sha256='0'*64;$mismatchCheck=Test-TsfRuntimeStorageManifest $manifestMismatch $compactPacket.packet_directory
Assert-Case 'VS-STORAGE-008' storage (!$mismatchCheck.valid-and@($mismatchCheck.errors|Where-Object{$_-match'collision|identity'}).Count-gt0) 'short-key/full-digest collision mismatch fails closed'
$legacyDescriptor=Get-TsfPreservationPacketDescriptor $mapperPreservationPath $readMission.mission_id $readMission.mission_revision
Assert-Case 'VS-STORAGE-009' storage ($legacyDescriptor.layout-eq'LEGACY_READ_ONLY') 'historical preservation packet remains readable only through compatibility descriptor'
Assert-Case 'VS-STORAGE-010' storage ((Split-Path -Leaf $compactPacket.packet_file)-eq'pp.json'-and$compactPacket.packet_directory-match'[\\/]p[\\/][a-z2-7]{32}[\\/][a-z2-7]{32}$') 'new preservation writes enforce compact V1 layout'
$tempRun='temp-preservation-failure';$tempPlan=New-TsfRuntimeStoragePlan $compactRoot $readMission.mission_id $readMission.mission_revision $tempRun;$tempPreservationFailed=Throws{Write-TsfKernelPreservationPacket -MissionPath $compactMissionPath -PreflightResultPath $compactPreflight -OutputDirectory $compactRoot -RunId $tempRun -DurableMission $readMission -TestFault TEMP_WRITE}
Assert-Case 'VS-STORAGE-011' storage ($tempPreservationFailed-and!(Test-Path $tempPlan.directory)-and!(Test-Path $tempPlan.staging_directory)) 'temporary preservation failure occurs before any packet write'
$recoveryRun='finalization-recovery';$recoveryPlan=New-TsfRuntimeStoragePlan $compactRoot $readMission.mission_id $readMission.mission_revision $recoveryRun;$finalPreservationFailed=Throws{Write-TsfKernelPreservationPacket -MissionPath $compactMissionPath -PreflightResultPath $compactPreflight -WorkerResultPath $compactWorker -VerifierResultPath $compactVerifier -OutputDirectory $compactRoot -RunId $recoveryRun -DurableMission $readMission -TestFault FINALIZE}
$recoveredPacket=Write-TsfKernelPreservationPacket -MissionPath $compactMissionPath -PreflightResultPath $compactPreflight -WorkerResultPath $compactWorker -VerifierResultPath $compactVerifier -OutputDirectory $compactRoot -RunId $recoveryRun -DurableMission $readMission
Assert-Case 'VS-STORAGE-012' storage ($finalPreservationFailed-and$recoveredPacket.recovered_from_staging-and(Test-Path $recoveryPlan.directory)-and!(Test-Path $recoveryPlan.staging_directory)) 'verified staging packet reconciles idempotently after finalization failure'

$compactResult=Copy-Object $mapperResult;$compactResult.preservation_evidence.packet_path=$compactPacket.packet_file;$compactResult.preservation_evidence.packet_sha256=Get-Hash $compactPacket.packet_file
$compactDurable=Add-TsfRuntimeDurableResult $compactResult $compactPacket.packet_file;Assert-Case 'VS-STORAGE-013' storage ((Split-Path -Leaf $compactDurable.path)-eq'dr.json'-and(Test-Path $compactDurable.path)) 'durable result is inserted transactionally at the compact canonical address'
$compactAdmissionRoot=Join-Path $runtimeRoot 'compact-admission';$compactQueueRoot=Join-Path $compactAdmissionRoot 'queue';$compactQueuePath=Join-Path $compactQueueRoot 'postrun_pending\m.json';Write-Json $readQueue $compactQueuePath;$compactRegistry=Join-Path $compactAdmissionRoot 'registry';Write-Json $readMission (Join-Path $compactRegistry 'm.json');$compactLedger=Join-Path $compactAdmissionRoot 'ledger.json';Write-Json ([pscustomobject]@{schema_version=1;ledger_id='compact-empty';approvals=@()}) $compactLedger
$compactAdmission=Get-TsfAdmissionDecision $compactDurable.path $compactRegistry (Join-Path $repo 'fleet\control\policy-manifest.v1.json') $compactLedger $compactQueuePath $compactQueueRoot -UnsupportedDevelopmentMode
Assert-Case 'VS-STORAGE-014' storage ($compactAdmission.status-eq'ADMITTED_WITH_CAVEATS'-and(Test-TsfKernelPathInside $compactAdmission.admission_receipt_path $compactPacket.packet_directory)-and(Test-Path $compactAdmission.transaction_receipt_path)) 'receipts are transactionally bound inside verified compact preservation packet'
$duplicateAuthorityHits=@(rg -n "Substring\(0,(32|40)\)|app_server_adapter_result\.json|preservation_packet\.json" (Join-Path $repo 'tools') 2>$null|Where-Object{$_-notmatch'TsfRuntimeArtifactAddressing.ps1'-and$_-notmatch'LEGACY'})
Assert-Case 'VS-STORAGE-015' storage ($duplicateAuthorityHits.Count-eq0) 'no duplicate short-key or descriptive runtime path authority remains in tools'

$sourceWorktree=Join-Path (Split-Path -Parent $repo) 'Thousand-Sunny-Fleet-durable-contract-v1-20260710'
$recoveryRecord=Join-Path $sourceWorktree '.codex-local\preservation\transactional-admission-resume-v1-20260711\synthetic-recovery.json'
Assert-Case 'VS-RECOVERY-001' recovery ((Test-Path -LiteralPath $recoveryRecord)-and((Get-Content -LiteralPath $recoveryRecord -Raw|ConvertFrom-Json).recovery_action-eq'RECREATE_EXACT_SYNTHETIC_FIXTURE_ROOT')) 'previous failed scratch transaction preserved and deterministically recreated'

function New-AdmissionFixture {
    param([string]$Name,[string]$ResultId,[string]$MissionId="synthetic-transaction-$Name",[int]$PreservationPadding=0,[int]$PacketFolderPadding=40)
    $mission=Copy-Object $readMission;$mission.mission_id=$MissionId;$mission.original_request="SYNTHETIC_TRANSACTION_$Name";$mission.normalized_goal='Exercise transactional admission only.';$mission.created_at=[datetimeoffset]::UtcNow.ToString('o');$mission.expires_at=[datetimeoffset]::UtcNow.AddMinutes(30).ToString('o')
    $root=Join-Path $runtimeRoot "transactional\$Name";$queueRoot=Join-Path $root 'queue';$queuePath=Join-Path $queueRoot 'postrun_pending\m.json';$document=ConvertTo-TsfCanonicalExecutionArtifacts $mission $repo;Write-Json $document $queuePath
    $registry=Join-Path $root 'registry';Write-Json $mission (Join-Path $registry 'm.json')
    $padding=if($PreservationPadding){'p'*$PreservationPadding}else{'p'};$preservationRoot=Join-Path $root "$padding\preservation";$packetFolder=Join-Path $preservationRoot ('packet-'+'q'*$PacketFolderPadding);$packetPath=Join-Path $packetFolder 'preservation_packet.json';Write-Json ([pscustomobject]@{mission_id=$mission.mission_id;final_decision='GREEN'}) $packetPath
    $result=Copy-Object $mapperResult;$result.result_id=$ResultId;$result.mission_id=$mission.mission_id;$result.mission_revision=$mission.mission_revision;$result.mission_content_hash=Get-TsfContractJsonHash $mission;$result.policy_fingerprint=$mission.policy.fingerprint;$result.preservation_evidence.packet_path=$packetPath;$result.preservation_evidence.packet_sha256=Get-Hash $packetPath;$result.created_at=[datetimeoffset]::UtcNow.ToString('o')
    $resultPath=Join-Path $root 'result.json';Write-Json $result $resultPath;$ledger=Join-Path $root 'ledger.json';Write-Json ([pscustomobject]@{schema_version=1;ledger_id="ledger-$Name";approvals=@()}) $ledger
    [pscustomobject]@{root=$root;mission=$mission;result=$result;result_path=$resultPath;registry=$registry;queue_root=$queueRoot;queue_path=$queuePath;ledger=$ledger;preservation_root=$preservationRoot;packet_path=$packetPath}
}
function Invoke-AdmissionFixture($Fixture,[string]$Fault='NONE',[string]$QueuePath=''){
    if(!$QueuePath){$QueuePath=$Fixture.queue_path}
    Get-TsfAdmissionDecision $Fixture.result_path $Fixture.registry (Join-Path $repo 'fleet\control\policy-manifest.v1.json') $Fixture.ledger $QueuePath $Fixture.queue_root -UnsupportedDevelopmentMode -TestFault $Fault
}

$longMissionId='synthetic-'+('m'*110);$longResultId='r'+('x'*150);$txLong=New-AdmissionFixture 'long' $longResultId $longMissionId
$txReceipt=Invoke-AdmissionFixture $txLong
$receiptLeaf=Split-Path -Leaf $txReceipt.admission_receipt_path;$receiptKey=$receiptLeaf.Substring(2,32);$receiptRoot=Split-Path -Parent $txReceipt.admission_receipt_path;$allReceiptPaths=@('a','t','x','y','z','c'|ForEach-Object{Join-Path $receiptRoot "$_-$receiptKey.$(if($_-in@('a','t','c')){'json'}else{'tmp'})"});$maximumReceiptPath=($allReceiptPaths|ForEach-Object{$_.Length}|Measure-Object -Maximum).Maximum
Assert-Case 'VS-TX-001' transaction ($maximumReceiptPath-le240-and$maximumReceiptPath-le225-and$receiptLeaf-match'^a-[a-z2-7]{32}\.json$') "160-bit deterministic Base32 key; max path $maximumReceiptPath"
Assert-Case 'VS-TX-001A' transaction ($txReceipt.receipt_identity_sha256.Length-eq64-and(ConvertTo-TsfRuntimeShortKey $txReceipt.receipt_identity_sha256)-eq$receiptKey-and$txReceipt.receipt_id-match'^admission-[a-z2-7]{24}$') 'full SHA-256 identity retained and matches short key'
$txMarker=Get-Content $txReceipt.transaction_receipt_path -Raw|ConvertFrom-Json
Assert-Case 'VS-TX-002' transaction ((Test-Path -LiteralPath $txReceipt.admission_receipt_path)-and(Test-Path -LiteralPath $txReceipt.transaction_receipt_path)-and$txMarker.state-eq'COMMITTED'-and$txMarker.receipt_identity_sha256-eq$txReceipt.receipt_identity_sha256) 'queue and both mandatory receipts committed with matching full digest'
$originalReceiptHash=Get-Hash $txReceipt.admission_receipt_path;$exact=Invoke-AdmissionFixture $txLong 'NONE' $txReceipt.queue_transition_path
Assert-Case 'VS-TX-003' replay ($exact.idempotent_replay-and$exact.result_sha256-eq$txReceipt.result_sha256-and(Get-Hash $txReceipt.admission_receipt_path)-eq$originalReceiptHash) 'exact replay returns preserved original decision'
$changed=Copy-Object $txLong.result;$changed.proposed_next_action='conflicting transaction replay';Write-Json $changed $txLong.result_path;$conflict=Invoke-AdmissionFixture $txLong 'NONE' $txReceipt.queue_transition_path
Assert-Case 'VS-TX-004' replay ($conflict.status-eq'REJECTED_INVALID_EVIDENCE'-and$conflict.conflict_identity_sha256.Length-eq64-and(Split-Path -Leaf $conflict.conflict_receipt_path)-match'^c-[a-z2-7]{32}\.json$'-and(Test-Path -LiteralPath $conflict.original_admission_receipt_path)-and(Get-Hash $txReceipt.admission_receipt_path)-eq$originalReceiptHash) 'conflicting result ID preserves original and writes collision-checked immutable conflict'

$txTemp=New-AdmissionFixture 'temp-failure' 'transaction-temp-failure-result';$tempFailed=Throws{Invoke-AdmissionFixture $txTemp 'TEMP_WRITE'}
Assert-Case 'VS-TX-005' transaction ($tempFailed-and(Test-Path $txTemp.queue_path)-and!(Test-Path (Join-Path $txTemp.queue_root 'complete_ready_for_gate\m.json'))) 'temporary receipt failure occurs before queue movement'
$txQueue=New-AdmissionFixture 'queue-failure' 'transaction-queue-failure-result';$queueFailed=Throws{Invoke-AdmissionFixture $txQueue 'QUEUE_TRANSITION'}
Assert-Case 'VS-TX-006' transaction ($queueFailed-and(Test-Path $txQueue.queue_path)-and!(Test-Path (Join-Path $txQueue.queue_root 'complete_ready_for_gate\m.json'))) 'simulated transition failure leaves queue unadvanced'
$txFinalize=New-AdmissionFixture 'finalize-failure' 'transaction-finalize-failure-result';$finalizeFailed=Throws{Invoke-AdmissionFixture $txFinalize 'FINALIZE_ADMISSION'}
$finalizeAdmission=Get-ChildItem -LiteralPath $txFinalize.preservation_root -Filter 'a-*.json' -File -Recurse|Select-Object -First 1
Assert-Case 'VS-TX-007' transaction ($finalizeFailed-and(Test-Path $txFinalize.queue_path)-and!(Test-Path (Join-Path $txFinalize.queue_root 'complete_ready_for_gate\m.json'))-and!$finalizeAdmission) 'final receipt failure rolls queue back through bound recovery'
$txCommit=New-AdmissionFixture 'commit-failure' 'transaction-commit-failure-result';$commitFailed=Throws{Invoke-AdmissionFixture $txCommit 'FINALIZE_TRANSACTION'};$commitReceipt=Get-ChildItem -LiteralPath $txCommit.preservation_root -Filter 'a-*.json' -File -Recurse|Select-Object -First 1;$commitMarker=Get-ChildItem -LiteralPath $txCommit.preservation_root -Filter 't-*.json' -File -Recurse|Select-Object -First 1;$commitState=Get-Content $commitMarker.FullName -Raw|ConvertFrom-Json;$reconciled=Invoke-AdmissionFixture $txCommit 'NONE' $commitState.destination_path
Assert-Case 'VS-TX-008' transaction ($commitFailed-and$commitReceipt-and$commitState.state-eq'RECOVERY_REQUIRED'-and$reconciled.idempotent_replay-and((Get-Content $commitMarker.FullName -Raw|ConvertFrom-Json).state-eq'COMMITTED')) 'idempotent retry reconciles durable recovery marker'

$txBudget=New-AdmissionFixture 'budget' 'transaction-budget-result' -PreservationPadding 38 -PacketFolderPadding 1;$budgetFailed=Throws{Invoke-AdmissionFixture $txBudget}
Assert-Case 'VS-TX-009' transaction ($budgetFailed-and(Test-Path $txBudget.queue_path)-and!(Test-Path (Join-Path $txBudget.queue_root 'complete_ready_for_gate\m.json'))) 'path budget rejected before queue movement'
$txCollision=New-AdmissionFixture 'collision' 'transaction-collision-result';$identity=[pscustomobject][ordered]@{mission_id=$txCollision.result.mission_id;mission_revision=[int]$txCollision.result.mission_revision;result_id=$txCollision.result.result_id;policy_fingerprint=$txCollision.result.policy_fingerprint;preservation_packet_sha256=$txCollision.result.preservation_evidence.packet_sha256};$fullKey=Get-TsfContractJsonHash $identity;$key=ConvertTo-TsfRuntimeShortKey $fullKey;$receiptRoot=Join-Path $txCollision.preservation_root 'r';Write-Json ([pscustomobject]@{receipt_identity_sha256=('0'*64);result_sha256=Get-Hash $txCollision.result_path}) (Join-Path $receiptRoot "a-$key.json");$collisionFailed=Throws{Invoke-AdmissionFixture $txCollision}
Assert-Case 'VS-TX-010' transaction ($collisionFailed-and(Test-Path $txCollision.queue_path)) 'explicit receipt identity collision fails closed'
Assert-Case 'VS-TX-011' transaction (!(Get-Command Get-TsfAdmissionDecision).Parameters.ContainsKey('PreservationPacketPath')) 'caller cannot substitute receipt root'

function Invoke-LiveCase {
    param([object]$Mission,[string]$Label)
    $caseRoot=Join-Path $runtimeRoot "$Label\evidence";$queueRoot=Join-Path $runtimeRoot "$Label\queue";$inbox=Join-Path $queueRoot 'inbox';New-Item -ItemType Directory -Force $inbox,$caseRoot|Out-Null
    $document=ConvertTo-TsfCanonicalExecutionArtifacts $Mission $repo;$queuePath=Join-Path $inbox "$($Mission.mission_id).json";Write-Json $document $queuePath
    $ledgerPath=Join-Path $caseRoot 'approval-ledger.json';Write-Json ([pscustomobject]@{schema_version=1;ledger_id="$Label-empty-ledger";approvals=@()}) $ledgerPath
    $outFile=Join-Path $caseRoot 'queue_executor_result.json';$output=@(& powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $repo 'tools\Invoke-TsfMissionQueueForegroundExecutor.ps1') -MissionPath $queuePath -QueueRoot $queueRoot -ApprovalLedgerPath $ledgerPath -OutDirectory $caseRoot -OutFile $outFile -RunCanonicalAppServerWorker -UnsupportedDevelopmentMode -WorkerTimeoutSeconds 180 2>&1);$exit=$LASTEXITCODE
    $result=if(Test-Path $outFile){Get-Content $outFile -Raw|ConvertFrom-Json}else{$null}
    return [pscustomobject]@{exit=$exit;output=$output;result=$result;mission=$Mission;document=$document;case_root=$caseRoot;queue_root=$queueRoot;ledger=$ledgerPath}
}

$readCase=$null;$writeCase=$null;$readGreen=$false
if($RunLiveReadOnly){
    $readCase=Invoke-LiveCase $readMission 'read-only';$readGreen=$readCase.exit-eq0-and$null-ne$readCase.result-and[string]$readCase.result.final_decision-eq'GREEN'
    Assert-Case 'VS-LIVE-RO-001' live_readonly $readGreen ($readCase.output -join ' ')
    if($readGreen){$lifecycle=Get-Content $readCase.result.lifecycle_result_path -Raw|ConvertFrom-Json;$adapter=Get-Content $lifecycle.adapter_result_path -Raw|ConvertFrom-Json;$durable=Get-Content $readCase.result.durable_result_path -Raw|ConvertFrom-Json
        Assert-Case 'VS-LIVE-RO-002' live_readonly ($adapter.final_response.Trim()-eq'TSF_READ_ONLY_ROUND_TRIP_GREEN') $adapter.final_response
        Assert-Case 'VS-LIVE-RO-003' live_readonly ($adapter.thread_id-and$adapter.turn_id-and$adapter.event_count-gt0) "$($adapter.thread_id):$($adapter.turn_id)"
        Assert-Case 'VS-LIVE-RO-004' live_readonly ($adapter.control_plane_service_network_policy-eq'CODEX_SERVICE_ONLY'-and$adapter.worker_tool_network_policy-eq'DISABLED'-and$adapter.codex_service_connection_used-and!$adapter.worker_network_used) 'network planes separated'
        Assert-Case 'VS-LIVE-RO-005' live_readonly ($adapter.child_exited-and$adapter.no_orphan_process) 'child cleanup'
        Assert-Case 'VS-LIVE-RO-006' live_readonly ($durable.model_assurance_level-eq'ADAPTER_VERIFIED'-and$durable.actual_model-eq$readMission.resolved_model-and$durable.actual_reasoning_effort-eq'UNKNOWN'-and$durable.effort_evidence.mission_requested_effort-eq'LIGHT'-and$durable.effort_evidence.canonical_resolved_effort-eq'LIGHT'-and$durable.effort_evidence.turn_requested_effort-eq'low'-and$durable.effort_evidence.effective_effort-eq'UNKNOWN'-and$durable.effort_evidence.effective_effort_source-eq'NOT_EXPOSED'-and$durable.effort_evidence.effort_assurance-eq'RECOMMENDED_ONLY') 'model observed and effort uncertainty preserved'
        Assert-Case 'VS-LIVE-RO-007' live_readonly ($readCase.result.admission_status-eq'ADMITTED_WITH_CAVEATS'-and$readCase.result.final_queue_state-eq'complete_ready_for_gate') 'admission caveat and queue transition'
        Assert-Case 'VS-LIVE-RO-008' live_readonly ($adapter.turn_usage.evidence_classification-eq'NATIVE_OBSERVED'-and$adapter.turn_usage.total_tokens-gt0-and$adapter.turn_usage.raw_payload_sha256-and$durable.usage_evidence.total_tokens-eq$adapter.turn_usage.total_tokens) 'bound native usage surfaced in adapter and durable result'
        $liveAdmissionPath=[string]$readCase.result.admission_receipt.admission_receipt_path;$liveTransactionPath=[string]$readCase.result.admission_receipt.transaction_receipt_path
        Assert-Case 'VS-LIVE-RO-009' live_readonly ((Test-Path -LiteralPath $liveAdmissionPath)-and(Test-Path -LiteralPath $liveTransactionPath)-and((Get-Content $liveTransactionPath -Raw|ConvertFrom-Json).state-eq'COMMITTED')) 'mandatory short receipts durably committed'
        $runtimeEvidence=Get-Content $readCase.result.runtime_evidence_path -Raw|ConvertFrom-Json
        $spoofAdapter=Get-Content $runtimeEvidence.adapter_result_path -Raw|ConvertFrom-Json;$spoofAdapter.observed_model='spoofed-model';$spoofAdapterPath=Join-Path $runtimeRoot 'spoof-adapter.json';Write-Json $spoofAdapter $spoofAdapterPath;$spoofEvidence=Copy-Object $runtimeEvidence;$spoofEvidence.adapter_result_path=$spoofAdapterPath;Assert-Case 'VS-EVIDENCE-001' evidence (Throws {ConvertTo-TsfDurableResultEnvelope $readMission $spoofEvidence $repo}) 'adapter spoof rejected'
        $spoofVerifier=Get-Content $runtimeEvidence.verifier_result_path -Raw|ConvertFrom-Json;$spoofVerifier.mission_id='spoofed-mission';$spoofVerifierPath=Join-Path $runtimeRoot 'spoof-verifier.json';Write-Json $spoofVerifier $spoofVerifierPath;$verifierEvidence=Copy-Object $runtimeEvidence;$verifierEvidence.verifier_result_path=$spoofVerifierPath;Assert-Case 'VS-EVIDENCE-002' evidence (Throws {ConvertTo-TsfDurableResultEnvelope $readMission $verifierEvidence $repo}) 'verifier spoof rejected'
        $spoofPres=Get-Content $runtimeEvidence.preservation_packet_path -Raw|ConvertFrom-Json;$spoofPres.mission_id='spoofed-mission';$spoofPresPath=Join-Path $runtimeRoot 'spoof-preservation.json';Write-Json $spoofPres $spoofPresPath;$presEvidence=Copy-Object $runtimeEvidence;$presEvidence.preservation_packet_path=$spoofPresPath;Assert-Case 'VS-EVIDENCE-003' evidence (Throws {ConvertTo-TsfDurableResultEnvelope $readMission $presEvidence $repo}) 'preservation mismatch rejected'
        $registry=Join-Path $readCase.case_root 'durable_mission_registry';$resultPath=$readCase.result.durable_result_path;$originalReceiptPath=[string]$readCase.result.admission_receipt.admission_receipt_path;$originalReceiptHash=Get-Hash $originalReceiptPath;$exact=Get-TsfAdmissionDecision $resultPath $registry (Join-Path $repo 'fleet\control\policy-manifest.v1.json') $readCase.ledger $readCase.result.final_queue_mission_path $readCase.queue_root -UnsupportedDevelopmentMode;Assert-Case 'VS-REPLAY-002' replay ($exact.idempotent_replay-and$exact.status-eq'ADMITTED_WITH_CAVEATS') 'exact replay idempotent'
        $changed=Copy-Object $durable;$changed.proposed_next_action='conflicting replay';$changedPath=Join-Path $runtimeRoot 'conflicting-result.json';Write-Json $changed $changedPath;$conflict=Get-TsfAdmissionDecision $changedPath $registry (Join-Path $repo 'fleet\control\policy-manifest.v1.json') $readCase.ledger $readCase.result.final_queue_mission_path $readCase.queue_root -UnsupportedDevelopmentMode;Assert-Case 'VS-REPLAY-003' replay ($conflict.status-eq'REJECTED_INVALID_EVIDENCE'-and(Get-Hash $originalReceiptPath)-eq$originalReceiptHash-and(Test-Path -LiteralPath $conflict.conflict_receipt_path)) 'conflicting replay preserves original'
        $approvalBound=Copy-Object $readMission;$approvalBound.approval_references=@([pscustomobject]@{approval_id='approval-fixture-vertical';exact_action='local_write'});$approvalQueue=ConvertTo-TsfCanonicalExecutionArtifacts $approvalBound $repo;$approvalRoot=Join-Path $runtimeRoot 'missing-approval';$approvalQueueRoot=Join-Path $approvalRoot 'queue';$approvalQueuePath=Join-Path $approvalQueueRoot 'postrun_pending\mission.json';Write-Json $approvalQueue $approvalQueuePath;$approvalRegistry=Join-Path $approvalRoot 'registry';Write-Json $approvalBound (Join-Path $approvalRegistry 'mission.json');$approvalResult=Copy-Object $durable;$approvalResult.result_id='missing-required-approval-result';$approvalResult.mission_content_hash=Get-TsfContractJsonHash $approvalBound;$approvalResult.approval_use=@();$approvalLegacyPacket=Join-Path $approvalRoot 'preservation\packet\preservation_packet.json';Write-Json ([pscustomobject]@{mission_id=$approvalBound.mission_id;final_decision='GREEN'}) $approvalLegacyPacket;$approvalResult.preservation_evidence.packet_path=$approvalLegacyPacket;$approvalResult.preservation_evidence.packet_sha256=Get-Hash $approvalLegacyPacket;$approvalResultPath=Join-Path $approvalRoot 'result.json';Write-Json $approvalResult $approvalResultPath;$missingApproval=Get-TsfAdmissionDecision $approvalResultPath $approvalRegistry (Join-Path $repo 'fleet\control\policy-manifest.v1.json') $readCase.ledger $approvalQueuePath $approvalQueueRoot -UnsupportedDevelopmentMode;Assert-Case 'VS-APPROVAL-007' approval ($missingApproval.status-eq'TIM_REQUIRED'-and($missingApproval.reasons-join' ')-match'Every required approval') ($missingApproval.reasons-join'; ')
    }
}

if($RunLiveWorkspaceWrite-and$readGreen){
    $writeRepo=Join-Path $runtimeRoot 'workspace-write-repo';New-Item -ItemType Directory -Force (Join-Path $writeRepo 'input'),(Join-Path $writeRepo 'output')|Out-Null;Set-Content -LiteralPath (Join-Path $writeRepo 'input\source.txt') -Value 'synthetic input';& git -C $writeRepo init -q;& git -C $writeRepo config user.email 'fixture@tsf.invalid';& git -C $writeRepo config user.name 'TSF Fixture';& git -C $writeRepo add .;& git -C $writeRepo commit -q -m fixture;$writeBranch=(& git -C $writeRepo branch --show-current).Trim();$writeHead=(& git -C $writeRepo rev-parse HEAD).Trim();$writeMission=New-CanonicalMission 'synthetic-tsf-workspace-appserver-0001' $writeRepo $writeBranch $writeHead -WorkspaceWrite
    $writeCase=Invoke-LiveCase $writeMission 'workspace-write';$writeGreen=$writeCase.exit-eq0-and$null-ne$writeCase.result-and[string]$writeCase.result.final_decision-eq'GREEN';Assert-Case 'VS-LIVE-WR-001' live_workspace_write $writeGreen ($writeCase.output-join' ')
    if($writeGreen){$artifact=Join-Path $writeRepo 'output\result.txt';$adapter=Get-Content (Get-Content $writeCase.result.lifecycle_result_path -Raw|ConvertFrom-Json).adapter_result_path -Raw|ConvertFrom-Json;Assert-Case 'VS-LIVE-WR-002' live_workspace_write ((Get-Content $artifact -Raw).Trim()-eq'TSF workspace-write round trip complete.') 'exact fixture content';Assert-Case 'VS-LIVE-WR-003' live_workspace_write ($adapter.worker_tool_network_policy-eq'DISABLED'-and!$adapter.worker_network_used) 'worker network disabled';Assert-Case 'VS-LIVE-WR-004' live_workspace_write ($writeCase.result.admission_status-eq'ADMITTED_WITH_CAVEATS'-and$writeCase.result.final_queue_state-eq'complete_ready_for_gate') 'workspace admission with truthful effort caveat';Assert-Case 'VS-LIVE-WR-005' live_workspace_write ($adapter.turn_usage.evidence_classification-eq'NATIVE_OBSERVED'-and$adapter.turn_usage.total_tokens-gt0) 'workspace native usage observed';Assert-Case 'VS-LIVE-WR-006' live_workspace_write ((Test-Path -LiteralPath $writeCase.result.admission_receipt.admission_receipt_path)-and(Test-Path -LiteralPath $writeCase.result.admission_receipt.transaction_receipt_path)) 'workspace mandatory receipts persisted'}
}elseif($RunLiveWorkspaceWrite-and!$readGreen){Assert-Case 'VS-LIVE-WR-GATE' live_workspace_write $false 'read-only GREEN gate not satisfied'}

$script:Results|Export-Csv (Join-Path $EvidenceRoot 'EXECUTED_TEST_COVERAGE.csv') -NoTypeInformation -Encoding UTF8
$failed=@($script:Results|Where-Object status -ne 'PASS')
$capability=[pscustomobject]@{schema_version='tsf_app_server_capability_report_v1';codex_version='0.144.1';transport='stdio://';experimental_api=$false;stable_methods=@('initialize','model/list','thread/start','turn/start');read_only_attempted=[bool]$RunLiveReadOnly;read_only_green=$readGreen;workspace_write_attempted=[bool]($RunLiveWorkspaceWrite-and$readGreen);question_relay_status='QUESTION_RELAY_DEFERRED_AFTER_AUTOMATIC_ROUND_TRIP'};Write-Json $capability (Join-Path $EvidenceRoot 'APP_SERVER_CAPABILITY_REPORT.json')
$eventSummary=[pscustomobject]@{schema_version='tsf_app_server_event_summary_v1';read_only_thread_id=if($readGreen){[string]$readCase.result.thread_id}else{''};read_only_turn_id=if($readGreen){[string]$readCase.result.turn_id}else{''};workspace_thread_id=if($null-ne$writeCase-and$writeCase.result){[string]$writeCase.result.thread_id}else{''};workspace_turn_id=if($null-ne$writeCase-and$writeCase.result){[string]$writeCase.result.turn_id}else{''};all_children_exited=if($readGreen){[bool]$readCase.result.child_exited-and($null-eq$writeCase-or[bool]$writeCase.result.child_exited)}else{$false};no_orphan_process=if($readGreen){[bool]$readCase.result.no_orphan_process-and($null-eq$writeCase-or[bool]$writeCase.result.no_orphan_process)}else{$false}};Write-Json $eventSummary (Join-Path $EvidenceRoot 'APP_SERVER_EVENT_SUMMARY.json')
$validation=[pscustomobject]@{schema_version='tsf_canonical_runtime_app_server_vertical_slice_validation_v1';generated_at=[datetimeoffset]::UtcNow.ToString('o');verdict=if($failed.Count){'RED'}elseif($RunLiveReadOnly-and$readGreen-and(!$RunLiveWorkspaceWrite-or$null-ne$writeCase)){'GREEN'}else{'YELLOW'};executed_assertion_count=$script:Results.Count;passed_assertion_count=@($script:Results|Where-Object status -eq 'PASS').Count;failed_assertion_count=$failed.Count;fingerprint=$fingerprint.fingerprint;fingerprint_content_source=$fingerprint.content_source;read_only_green=$readGreen;workspace_write_green=if($null-ne$writeCase-and$writeCase.result){[string]$writeCase.result.final_decision-eq'GREEN'}else{$false};control_plane_service_network_policy='CODEX_SERVICE_ONLY';worker_tool_network_policy='DISABLED';direct_openai_api_called_by_tsf=$false;external_api_called=$false;worker_network_used=$false;push_performed=$false;merge_performed=$false;package_installed=$false;listener_opened=$false;persistent_process_started=$false;work_integration_performed=$false;plugin_or_mcp_added=$false;nwr_accessed=$false;privatelens_content_accessed=$false;product_repository_mutated=$false;deployment_performed=$false};Write-Json $validation (Join-Path $EvidenceRoot 'VALIDATION.json')
if($failed.Count){throw "$($failed.Count) canonical vertical-slice assertions failed."}
Write-Host "Canonical vertical-slice tests passed: $($script:Results.Count) assertions."
