[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"

function Resolve-GameForgePath {
    param(
        [string]$Root,
        [string]$Path
    )

    if ([string]::IsNullOrWhiteSpace($Path)) {
        return $Path
    }

    if ([System.IO.Path]::IsPathRooted($Path)) {
        return $Path
    }

    return Join-Path $Root $Path
}

function ConvertTo-GameForgeSlug {
    param([string]$Name)

    $slug = ([string]$Name).Trim().ToLowerInvariant()
    $slug = [regex]::Replace($slug, "[^a-z0-9]+", "-").Trim("-")
    if ([string]::IsNullOrWhiteSpace($slug)) {
        return "game-project"
    }

    return $slug
}

function Get-GameForgeIntakeValue {
    param(
        [string]$Text,
        [string]$Label,
        [string]$Default = "unknown"
    )

    $match = [regex]::Match($Text, "(?im)^\s*-\s+$([regex]::Escape($Label))\s*:\s*(.+?)\s*$")
    if ($match.Success) {
        return $match.Groups[1].Value.Trim()
    }

    return $Default
}

function Get-GameForgeIntake {
    param(
        [string]$FleetRoot,
        [string]$IntakePath
    )

    $fleetRootFull = (Resolve-Path -LiteralPath $FleetRoot).Path
    if ([string]::IsNullOrWhiteSpace($IntakePath)) {
        $IntakePath = Join-Path $fleetRootFull "tests\fixtures\fleet\game-forge\nytheria-intake.md"
    } else {
        $IntakePath = Resolve-GameForgePath -Root $fleetRootFull -Path $IntakePath
    }

    if (!(Test-Path -LiteralPath $IntakePath)) {
        throw "Game Forge intake not found: $IntakePath"
    }

    $text = Get-Content -LiteralPath $IntakePath -Raw -ErrorAction Stop
    $name = Get-GameForgeIntakeValue -Text $text -Label "Game name" -Default "Nytheria"

    return [pscustomobject]@{
        sourcePath = $IntakePath
        rawText = $text
        gameName = $name
        slug = ConvertTo-GameForgeSlug -Name $name
        aliases = Get-GameForgeIntakeValue -Text $text -Label "Old names / aliases" -Default "none"
        genre = Get-GameForgeIntakeValue -Text $text -Label "Genre" -Default "unknown"
        camera = Get-GameForgeIntakeValue -Text $text -Label "Camera/view style" -Default "unknown"
        mode = Get-GameForgeIntakeValue -Text $text -Label "Single-player/co-op/multiplayer" -Default "unknown"
        platform = Get-GameForgeIntakeValue -Text $text -Label "Target platform" -Default "unknown"
        promise = Get-GameForgeIntakeValue -Text $text -Label "Core fantasy / player promise" -Default "unknown"
        world = Get-GameForgeIntakeValue -Text $text -Label "World structure" -Default "unknown"
        combat = Get-GameForgeIntakeValue -Text $text -Label "Combat style" -Default "unknown"
        progression = Get-GameForgeIntakeValue -Text $text -Label "Progression style" -Default "unknown"
        aiNeeds = Get-GameForgeIntakeValue -Text $text -Label "AI/living-world needs" -Default "unknown"
        canon = Get-GameForgeIntakeValue -Text $text -Label "Lore/canon constraints" -Default "unknown"
        saveLoad = Get-GameForgeIntakeValue -Text $text -Label "Save/load expectations" -Default "unknown"
        pipeline = Get-GameForgeIntakeValue -Text $text -Label "Modding/content pipeline needs" -Default "unknown"
        prototypeGoal = Get-GameForgeIntakeValue -Text $text -Label "Prototype goal" -Default "unknown"
        offLimits = Get-GameForgeIntakeValue -Text $text -Label "Off-limits" -Default "full engine until toy simulations prove the loop"
        mustAskTim = Get-GameForgeIntakeValue -Text $text -Label "Must-ask-Tim decisions" -Default "canon and prototype priority"
    }
}

function Get-GameForgeNytheriaModules {
    return @(
        "World Clock",
        "Faction Simulator",
        "God/Faith System",
        "Rumor System",
        "NPC Memory",
        "Origin/Race/Class Consequence System",
        "Default Timeline / Doom Clock",
        "Region State",
        "Encounter Director",
        "Lore Canon Layer",
        "Player Action Ledger"
    )
}

function Write-GameForgeLines {
    param(
        [string]$Path,
        [object[]]$Lines
    )

    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $Path) | Out-Null
    $cleanLines = @($Lines)
    while ($cleanLines.Count -gt 0 -and [string]::IsNullOrWhiteSpace([string]$cleanLines[$cleanLines.Count - 1])) {
        if ($cleanLines.Count -eq 1) {
            $cleanLines = @()
        } else {
            $cleanLines = @($cleanLines[0..($cleanLines.Count - 2)])
        }
    }
    $cleanLines | Set-Content -LiteralPath $Path -Encoding UTF8
    return $Path
}

function New-GameForgeBlueprintLines {
    param([object]$Intake)

    $modules = Get-GameForgeNytheriaModules
    return @(
        "# Engine Blueprint - $($Intake.gameName)",
        "",
        "Generated by TSF Game Forge V1 from TSF-local intake only. Evidence only; not executable authority or approval.",
        "",
        "## Intake Summary",
        "",
        "- Game name: $($Intake.gameName)",
        "- Old names / aliases: $($Intake.aliases)",
        "- Genre: $($Intake.genre)",
        "- Camera/view style: $($Intake.camera)",
        "- Target platform: $($Intake.platform)",
        "- Core promise: $($Intake.promise)",
        "",
        "## Recommended Engine Style",
        "",
        "- Data-driven simulation-first RPG cockpit.",
        "- Start text-only with deterministic fixtures before UI, combat, graphics, or AI game-master layers.",
        "- Treat lore as versioned evidence, approved canon, or adaptation proposal.",
        "",
        "## Core Runtime Loop",
        "",
        "1. Load world snapshot and canon registry.",
        "2. Advance World Clock by one tick or turn.",
        "3. Resolve faction goals, god/faith pressures, region changes, rumors, and timeline events.",
        "4. Apply player action ledger effects.",
        "5. Emit visible consequences, quest hooks, rumors, and changed world state.",
        "6. Save deterministic snapshot for replay and tests.",
        "",
        "## Data Model",
        "",
        "- GameState: clock, regions, factions, gods, rumors, NPC memory, quests, player ledger, doom-clock state.",
        "- CanonRegistry: root lore evidence, approved canon, adaptation proposals, source refs, alias mapping for Nytheris/Nytheria.",
        "- EventQueue: scheduled timeline events, war moves, divine interventions, rumor mutations.",
        "- PlayerActionLedger: choices, origin/race/class flags, faith acts, faction impacts, relationship impacts.",
        "",
        "## Content Pipeline",
        "",
        "- Store early content as plain markdown/json fixtures before editor tooling.",
        "- Require canon tier for lore entries: evidence, approved canon, adaptation proposal, rejected.",
        "- Keep old Nytheris lore as backbone evidence until Tim approves migration into Nytheria canon.",
        "",
        "## Save/Load Model",
        "",
        "- Snapshot GameState at turn boundaries.",
        "- Keep player action ledger append-only for auditability.",
        "- Add deterministic fixture saves for tests before any autosave UX.",
        "",
        "## Event System",
        "",
        "- Events have trigger, preconditions, effects, visibility, rumor output, and save/load serialization.",
        "- Default Timeline / Doom Clock events can fire without player involvement.",
        "",
        "## Quest / Story System",
        "",
        "- Quests are views over world state, faction goals, rumors, NPC memory, and player ledger.",
        "- Avoid authored story branches until canon tiers and world-state schema exist.",
        "",
        "## World Clock",
        "",
        "- Tick-based simulation clock with region, faction, faith, rumor, and timeline updates.",
        "- Supports paused inspection, deterministic replay, and fixture snapshots.",
        "",
        "## Simulation Boundaries",
        "",
        "- Prototype one region, two factions, one god/faith pressure, three rumor seeds, and one doom-clock arc.",
        "- No infinite procedural world, no full economy, no full combat, no multiplayer, no production AI GM.",
        "",
        "## AI Boundaries",
        "",
        "- AI can propose rumors, summaries, NPC recollections, or adaptation proposals.",
        "- AI must not rewrite approved canon, root lore, player ledger, or save-state truth without Tim approval.",
        "- AI output remains suggestion/evidence until validated into structured state.",
        "",
        "## Required Modules",
        "",
        @($modules | ForEach-Object { "- $_" }),
        "",
        "## Testing Strategy",
        "",
        "- Golden fixture for one world-clock tick.",
        "- Faction turn deterministic tests.",
        "- Rumor mutation snapshot tests.",
        "- NPC memory append/read tests.",
        "- Save/load round-trip tests.",
        "- Canon tier validation tests.",
        "",
        "## Prototype Milestone Plan",
        "",
        "1. Text-only world clock prototype.",
        "2. Faction turn simulator.",
        "3. Rumor propagation simulation.",
        "4. NPC memory toy model.",
        "5. Default Timeline / Doom Clock.",
        "6. Origin-based opening state generator.",
        "7. Lore canon registry.",
        "",
        "## What Not To Build Yet",
        "",
        "- Full game engine.",
        "- Real-time AI dungeon master.",
        "- Full combat engine.",
        "- Multiplayer.",
        "- Infinite procedural lore.",
        "- Graphics pipeline.",
        "- Production content editor.",
        "- Any system that rewrites canon without Tim approval."
    )
}

function Write-GameForgeEngineBlueprint {
    param(
        [string]$FleetRoot,
        [string]$IntakePath,
        [string]$OutDirectory
    )

    $fleetRootFull = (Resolve-Path -LiteralPath $FleetRoot).Path
    $intake = Get-GameForgeIntake -FleetRoot $fleetRootFull -IntakePath $IntakePath
    if ([string]::IsNullOrWhiteSpace($OutDirectory)) {
        $OutDirectory = Join-Path $fleetRootFull "fleet\status\game-forge\blueprints"
    } else {
        $OutDirectory = Resolve-GameForgePath -Root $fleetRootFull -Path $OutDirectory
    }

    $path = Join-Path $OutDirectory "$($intake.slug)-engine-blueprint.md"
    Write-GameForgeLines -Path $path -Lines (New-GameForgeBlueprintLines -Intake $intake)
}

function New-GameForgeSystemsMapLines {
    param([object]$Intake)

    $rows = @(
        @("World Clock", "Advance turns and fire scheduled events", "current snapshot, tick size", "new tick, due events", "clock, event queue", "all simulation systems", "cascading updates", "one deterministic tick", "calendar, seasons, long wars"),
        @("Faction Simulator", "Move factions toward goals", "faction goals, region state", "orders, conflicts, influence changes", "faction state", "World Clock, Region State", "too many factions too early", "two factions", "diplomacy, economy, alliances"),
        @("God/Faith System", "Track divine pressure and faith consequences", "faith acts, regions, factions", "omens, blessings, pressure", "faith state", "Player Ledger, Region State", "unclear theology canon", "one god pressure", "pantheon politics"),
        @("Rumor System", "Create and mutate rumors", "events, NPC memory, region state", "rumor records", "rumor graph", "World Clock, NPC Memory", "AI hallucinated canon", "three rumor seeds", "regional rumor networks"),
        @("NPC Memory", "Remember player and world events", "player actions, rumors, encounters", "memory entries, recalls", "NPC memory log", "Player Ledger, Rumor System", "unbounded memory", "append/read toy model", "summaries and decay"),
        @("Origin/Race/Class Consequence", "Shape opening state and reactions", "origin/race/class choice", "flags, starting relations", "character flags", "Quest System, Player Ledger", "hardcoded bias without canon", "opening generator", "long-term consequence rules"),
        @("Default Timeline / Doom Clock", "Move doomed timeline unless changed", "clock, unresolved events", "doom progress, warnings", "timeline state", "World Clock, Faction Simulator", "too punitive or unclear", "one doom arc", "branching timelines"),
        @("Region State", "Store control, danger, faith, rumors", "faction moves, events", "region snapshots", "region records", "Faction, Faith, Rumor", "state explosion", "two regions", "maps and travel"),
        @("Encounter Director", "Surface relevant encounters", "region, rumors, player flags", "encounter candidates", "encounter queue", "Region, Quest, NPC", "content demand", "text encounter list", "dynamic scenes"),
        @("Lore Canon Layer", "Separate evidence, canon, proposals", "root lore, Tim decisions", "canon registry", "canon records", "all content systems", "rewriting old lore", "tier registry", "editor and review workflow"),
        @("Player Action Ledger", "Append player choices", "player decisions", "auditable effects", "action log", "all consequence systems", "missing causality", "append-only log", "replay and diff tools"),
        @("Quest/Story System", "Expose stories from state", "world state, rumors, memory", "quests, hooks, resolutions", "quest records", "all systems", "story before schema", "state-derived hooks", "authored arcs")
    )

    $lines = @(
        "# Systems Map - $($Intake.gameName)",
        "",
        "Generated by TSF Game Forge V1. Evidence only; not executable authority or approval.",
        "",
        "| System | Responsibilities | Inputs | Outputs | Stored state | Dependencies | Risks | First prototype version | Later version |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |"
    )

    foreach ($row in $rows) {
        $lines += "| $($row[0]) | $($row[1]) | $($row[2]) | $($row[3]) | $($row[4]) | $($row[5]) | $($row[6]) | $($row[7]) | $($row[8]) |"
    }

    $lines += @(
        "",
        "## Required Flow Coverage",
        "",
        "- Player actions update the Player Action Ledger.",
        "- Faction goals alter region control and timeline pressure.",
        "- Gods/faith influence rumors, regions, and consequences.",
        "- Rumors mutate from events and NPC memory.",
        "- Timeline events and world state snapshots must be testable."
    )

    return $lines
}

function Write-GameForgeSystemsMap {
    param(
        [string]$FleetRoot,
        [string]$IntakePath,
        [string]$OutDirectory
    )

    $fleetRootFull = (Resolve-Path -LiteralPath $FleetRoot).Path
    $intake = Get-GameForgeIntake -FleetRoot $fleetRootFull -IntakePath $IntakePath
    if ([string]::IsNullOrWhiteSpace($OutDirectory)) {
        $OutDirectory = Join-Path $fleetRootFull "fleet\status\game-forge\system-maps"
    } else {
        $OutDirectory = Resolve-GameForgePath -Root $fleetRootFull -Path $OutDirectory
    }

    $path = Join-Path $OutDirectory "$($intake.slug)-systems-map.md"
    Write-GameForgeLines -Path $path -Lines (New-GameForgeSystemsMapLines -Intake $intake)
}

function Get-GameForgePrototypeSlices {
    return @(
        [pscustomobject]@{ name = "Text-only world clock prototype"; purpose = "Prove time advances and scheduled events fire."; scope = "One clock, two regions, three scheduled events."; files = "world-clock fixture, event fixture, markdown report"; validation = "golden output for tick 0 to tick 3" },
        [pscustomobject]@{ name = "Faction turn simulator"; purpose = "Prove factions pursue goals without the player."; scope = "Two factions, one contested region, simple influence scores."; files = "faction data fixture, region state fixture"; validation = "deterministic faction turn snapshot" },
        [pscustomobject]@{ name = "Rumor propagation simulation"; purpose = "Prove rumors mutate from events without becoming canon."; scope = "Three rumor seeds across two regions."; files = "rumor fixture, event fixture"; validation = "mutation output labels rumor as rumor, not canon" },
        [pscustomobject]@{ name = "NPC memory toy model"; purpose = "Prove NPCs remember bounded facts."; scope = "Two NPCs, append-only memory, simple recall."; files = "npc fixture, player action ledger fixture"; validation = "memory append/read round trip" },
        [pscustomobject]@{ name = "Default timeline / doom clock"; purpose = "Prove world can worsen without player action."; scope = "One doom track for human regions."; files = "timeline fixture, region state fixture"; validation = "doom advances unless intervention flag exists" },
        [pscustomobject]@{ name = "Origin-based opening state generator"; purpose = "Prove race/class/origin affect starting state."; scope = "Three origins, two classes, two race tags."; files = "origin fixture, character flags fixture"; validation = "opening state differs by origin/race/class" },
        [pscustomobject]@{ name = "Lore canon registry"; purpose = "Protect old lore while enabling proposals."; scope = "Evidence, approved canon, adaptation proposal, rejected tiers."; files = "canon registry fixture, Nytheris alias fixture"; validation = "old Nytheris lore remains evidence unless approved" }
    )
}

function New-GameForgePrototypeSliceLines {
    param([object]$Intake)

    $lines = @(
        "# Prototype Slices - $($Intake.gameName)",
        "",
        "Generated by TSF Game Forge V1. Evidence only; not executable authority or approval.",
        ""
    )

    $index = 0
    foreach ($slice in Get-GameForgePrototypeSlices) {
        $index++
        $lines += @(
            "## Slice $index - $($slice.name)",
            "",
            "- Purpose: $($slice.purpose)",
            "- Scope: $($slice.scope)",
            "- Acceptance criteria: A deterministic fixture proves the slice behavior and labels evidence vs canon correctly.",
            "- Files likely needed later: $($slice.files)",
            "- Risks: scope creep into full engine, canon confusion, unbounded AI output, missing save/load shape.",
            "- Stop conditions: real product repo needed, canon decision needed, install/deploy/secrets requested, or slice grows beyond one toy simulation.",
            "- Validation: $($slice.validation)",
            "",
            "Codex-ready work order:",
            "",
            "~~~text",
            "Project: $($Intake.gameName) Game Forge",
            "Goal: create TSF-local architecture or fixture notes for $($slice.name); do not build the real game engine.",
            "Files/artifacts: fleet/status/game-forge/; tests/fixtures/fleet/game-forge/nytheria-intake.md",
            "Off-limits: real Nytheria repo, product repo mutation, full engine implementation, installs, deploys, secrets, remote access.",
            "Stop conditions: needs real lore files not attached, canon decision required, or task expands beyond this slice.",
            "Validation: run TSF tests named by the work order.",
            "Final report: slice output, acceptance evidence, blockers, next safe slice.",
            "~~~",
            ""
        )
    }

    return $lines
}

function Write-GameForgePrototypeSlices {
    param(
        [string]$FleetRoot,
        [string]$IntakePath,
        [string]$OutDirectory
    )

    $fleetRootFull = (Resolve-Path -LiteralPath $FleetRoot).Path
    $intake = Get-GameForgeIntake -FleetRoot $fleetRootFull -IntakePath $IntakePath
    if ([string]::IsNullOrWhiteSpace($OutDirectory)) {
        $OutDirectory = Join-Path $fleetRootFull "fleet\status\game-forge\prototype-slices"
    } else {
        $OutDirectory = Resolve-GameForgePath -Root $fleetRootFull -Path $OutDirectory
    }

    $path = Join-Path $OutDirectory "$($intake.slug)-prototype-slices.md"
    Write-GameForgeLines -Path $path -Lines (New-GameForgePrototypeSliceLines -Intake $intake)
}

function New-GameForgeResearchPromptLines {
    param([object]$Intake)

    $topics = @(
        "living-world RPG feasibility",
        "game engine architecture for simulation-heavy RPGs",
        "NPC memory systems",
        "faction simulation",
        "quest/story event systems",
        "lore/canon database structure",
        "AI-assisted game master boundaries",
        "prototype roadmap",
        "comparable games and risks",
        "technical stack options"
    )

    $lines = @(
        "# Deep Research Prompts - $($Intake.gameName)",
        "",
        "Generated by TSF Game Forge V1. Deep Research cannot access local files unless Tim attaches them.",
        "Evidence only; not executable authority or approval.",
        ""
    )

    foreach ($topic in $topics) {
        $lines += @(
            "## Prompt - $topic",
            "",
            "Attach these files: tests/fixtures/fleet/game-forge/nytheria-intake.md, fleet/status/game-forge/templates/game-project-intake.md, and any Tim-approved lore/root files for $($Intake.gameName).",
            "",
            "Research $topic for a high-magic, low-tech, faction-driven living fantasy world RPG currently called $($Intake.gameName), previously $($Intake.aliases). Preserve old lore as evidence, separate approved canon from adaptation proposals, and recommend bounded prototype steps before any full engine work.",
            ""
        )
    }

    return $lines
}

function Write-GameForgeResearchPrompts {
    param(
        [string]$FleetRoot,
        [string]$IntakePath,
        [string]$OutDirectory
    )

    $fleetRootFull = (Resolve-Path -LiteralPath $FleetRoot).Path
    $intake = Get-GameForgeIntake -FleetRoot $fleetRootFull -IntakePath $IntakePath
    if ([string]::IsNullOrWhiteSpace($OutDirectory)) {
        $OutDirectory = Join-Path $fleetRootFull "fleet\status\game-forge\research-prompts"
    } else {
        $OutDirectory = Resolve-GameForgePath -Root $fleetRootFull -Path $OutDirectory
    }

    $path = Join-Path $OutDirectory "$($intake.slug)-research-prompts.md"
    Write-GameForgeLines -Path $path -Lines (New-GameForgeResearchPromptLines -Intake $intake)
}

function New-GameForgeRiskReviewLines {
    param([object]$Intake)

    $risks = @(
        @("TOO_BIG", "Trying to model the full living world before toy simulations prove the loop.", "Prototype one clock/faction/rumor slice first."),
        @("NEEDS_RESEARCH", "Simulation-heavy RPG architecture needs feasibility research.", "Use Deep Research prompts with attached intake and lore files."),
        @("NEEDS_CANON_DECISION", "Nytheris vs Nytheria source truth and canon tiers need Tim approval.", "Create canon registry before story implementation."),
        @("SAFE_PROTOTYPE", "Text-only toy simulations are safe TSF-local planning targets.", "Start with world clock and faction turn fixtures."),
        @("ENGINE_TRAP", "Building a full engine before data/schema fixtures will create churn.", "Keep outputs architecture-only until slices pass."),
        @("AI_SCOPE_TRAP", "AI could rewrite lore, invent canon, or create unbounded NPC memory.", "AI suggestions stay proposals until approved."),
        @("CONTENT_PIPELINE_RISK", "Lore, factions, regions, quests, and rumors need a content pipeline.", "Use plain fixtures and canon tiers first."),
        @("DATA_MODEL_RISK", "No world-state schema or save/load shape means consequences cannot be tested.", "Define GameState and snapshot fixtures early."),
        @("TESTING_GAP", "Living-world behavior is hard to trust without deterministic tests.", "Add golden fixtures for every toy simulation."),
        @("TIM_DECISION_REQUIRED", "Canon tiers, starting region, playable origins, faith boundaries, and doom timeline need Tim.", "Ask Tim before canon/story commitments.")
    )

    $lines = @(
        "# Game Risk Review - $($Intake.gameName)",
        "",
        "Generated by TSF Game Forge V1. Evidence only; not executable authority or approval.",
        "",
        "## Top Risks",
        "",
        "- Trying to build full living world too early.",
        "- AI rewriting lore without canon approval.",
        "- Building story before canon tiers.",
        "- Building a full engine before toy simulations.",
        "- Unbounded NPC memory.",
        "- No save/load model.",
        "- No world-state schema.",
        "- Confusing old Nytheris vs new Nytheria source truth.",
        "",
        "## Classifications",
        "",
        "| Classification | Risk | Safe response |",
        "| --- | --- | --- |"
    )

    foreach ($risk in $risks) {
        $lines += "| $($risk[0]) | $($risk[1]) | $($risk[2]) |"
    }

    return $lines
}

function Write-GameForgeRiskReview {
    param(
        [string]$FleetRoot,
        [string]$IntakePath,
        [string]$OutDirectory
    )

    $fleetRootFull = (Resolve-Path -LiteralPath $FleetRoot).Path
    $intake = Get-GameForgeIntake -FleetRoot $fleetRootFull -IntakePath $IntakePath
    if ([string]::IsNullOrWhiteSpace($OutDirectory)) {
        $OutDirectory = Join-Path $fleetRootFull "fleet\status\game-forge\risk-reviews"
    } else {
        $OutDirectory = Resolve-GameForgePath -Root $fleetRootFull -Path $OutDirectory
    }

    $path = Join-Path $OutDirectory "$($intake.slug)-risk-review.md"
    Write-GameForgeLines -Path $path -Lines (New-GameForgeRiskReviewLines -Intake $intake)
}

function New-GameForgeWorkOrderLines {
    param([object]$Intake)

    $orders = @(
        @("Research intake", "Summarize attached intake and research questions.", "Intake summary and source list exist."),
        @("Canon schema", "Define evidence, approved canon, adaptation proposal, rejected tiers.", "Nytheris alias remains evidence unless approved."),
        @("World-state schema", "Sketch GameState for clock, regions, factions, rumors, NPC memory, player ledger.", "Schema includes save/load fields."),
        @("Toy simulation", "Plan one deterministic world-clock or faction turn fixture.", "Golden expected output is named."),
        @("Static prototype UI", "Plan a non-executable cockpit view for world state.", "No browser command hooks or controls."),
        @("Save/load fixture", "Define snapshot and player action ledger round trip.", "Round-trip test is described."),
        @("Tests", "List deterministic tests for each toy system.", "No test needs product repo or install."),
        @("Docs", "Write usage notes and stop conditions.", "Docs say this is not a real engine.")
    )

    $lines = @(
        "# Game Work Orders - $($Intake.gameName)",
        "",
        "Generated by TSF Game Forge V1. Evidence only; not executable authority or approval.",
        "",
        "Do not create giant vague tasks. Do not ask Codex to build the engine.",
        ""
    )

    $index = 0
    foreach ($order in $orders) {
        $index++
        $lines += @(
            "## Work Order $index - $($order[0])",
            "",
            "~~~text",
            "Project: $($Intake.gameName) Game Forge",
            "Goal: $($order[1])",
            "Acceptance criteria: $($order[2])",
            "Files/artifacts: fleet/status/game-forge/; tests/fixtures/fleet/game-forge/nytheria-intake.md",
            "Off-limits: real game repo, product repo mutation, full engine implementation, installs, deploys, secrets, remote access, archived reactivation.",
            "Stop conditions: missing Tim-approved lore files, canon decision required, task becomes larger than one planning artifact, or forbidden action requested.",
            "Validation: powershell -NoProfile -ExecutionPolicy Bypass -File .\tests\run-fleet-tests.ps1",
            "Final report: artifact written, decisions needed, risks, next safe order.",
            "~~~",
            ""
        )
    }

    return $lines
}

function Write-GameForgeWorkOrders {
    param(
        [string]$FleetRoot,
        [string]$IntakePath,
        [string]$OutDirectory
    )

    $fleetRootFull = (Resolve-Path -LiteralPath $FleetRoot).Path
    $intake = Get-GameForgeIntake -FleetRoot $fleetRootFull -IntakePath $IntakePath
    if ([string]::IsNullOrWhiteSpace($OutDirectory)) {
        $OutDirectory = Join-Path $fleetRootFull "fleet\status\game-forge\work-orders"
    } else {
        $OutDirectory = Resolve-GameForgePath -Root $fleetRootFull -Path $OutDirectory
    }

    $path = Join-Path $OutDirectory "$($intake.slug)-game-work-orders.md"
    Write-GameForgeLines -Path $path -Lines (New-GameForgeWorkOrderLines -Intake $intake)
}

function Write-GameForgePack {
    param(
        [string]$FleetRoot,
        [string]$IntakePath
    )

    $fleetRootFull = (Resolve-Path -LiteralPath $FleetRoot).Path
    return [pscustomobject]@{
        blueprint = Write-GameForgeEngineBlueprint -FleetRoot $fleetRootFull -IntakePath $IntakePath
        systemsMap = Write-GameForgeSystemsMap -FleetRoot $fleetRootFull -IntakePath $IntakePath
        prototypeSlices = Write-GameForgePrototypeSlices -FleetRoot $fleetRootFull -IntakePath $IntakePath
        researchPrompts = Write-GameForgeResearchPrompts -FleetRoot $fleetRootFull -IntakePath $IntakePath
        riskReview = Write-GameForgeRiskReview -FleetRoot $fleetRootFull -IntakePath $IntakePath
        workOrders = Write-GameForgeWorkOrders -FleetRoot $fleetRootFull -IntakePath $IntakePath
    }
}
