[CmdletBinding(PositionalBinding = $false)]
param(
    [string]$MissionId = "",

    [Parameter(Mandatory = $true)]
    [string]$ProjectId,

    [Parameter(Mandatory = $true)]
    [string]$RepoPath,

    [Parameter(Mandatory = $true)]
    [ValidateSet("MASTER_TSF_CONTROL_PLANE", "TSF_NWR", "NORMAL_NWR", "PRODUCT_REPO", "PRIVATE_LENS", "OTHER")]
    [string]$Lane,

    [Parameter(Mandatory = $true)]
    [ValidateSet("tsf_infrastructure", "docs_control_plane", "review_only", "validation", "adapter", "null_fence", "admission_gate", "worker_handoff")]
    [string]$MissionType,

    [Parameter(Mandatory = $true)]
    [string[]]$AllowedReads,

    [string[]]$AllowedWrites = @(),

    [string[]]$ForbiddenReads = @("C:\NWR\Niners-War-Room"),

    [string[]]$ForbiddenWrites = @("C:\NWR\Niners-War-Room"),

    [string[]]$ForbiddenActions = @(),

    [Parameter(Mandatory = $true)]
    [string[]]$ExpectedArtifacts,

    [string[]]$RequiredPreflightChecks = @("schema", "repo_exists", "path_scope", "restricted_action_coverage", "git_status_capture", "approval_ledger"),

    [string[]]$RequiredPostrunChecks = @("mission_id_match", "expected_artifacts_exist", "restricted_actions_absent", "forbidden_outputs_absent"),

    [Parameter(Mandatory = $true)]
    [string[]]$StopCondition,

    [string[]]$ApprovalRequirement = @(),

    [ValidateSet("local_only_no_api", "hq_packet_required", "tim_required")]
    [string]$HqEscalationDefault = "local_only_no_api",

    [string[]]$HqEscalateOn = @("RED", "TIM_REQUIRED"),

    [string]$HqEscalationNotes = "Generated by TSF mission authoring helper.",

    [string]$CreatedBy = "TSF",

    [Parameter(Mandatory = $true)]
    [string]$OutFile,

    [switch]$ValidateShape
)

$ErrorActionPreference = "Stop"

$fleetRoot = Split-Path -Parent (Split-Path -Parent $PSCommandPath)
. (Join-Path $fleetRoot "tools\codex-fleet-enforcement-kernel.ps1")

function ConvertTo-AuthoringSlug {
    param([string]$Value)

    $slug = ([string]$Value).Trim().ToLowerInvariant() -replace "[^a-z0-9._:-]+", "-"
    $slug = $slug.Trim("-")
    if ([string]::IsNullOrWhiteSpace($slug)) {
        return "tsf-mission"
    }

    return $slug
}

function ConvertFrom-StopConditionSpec {
    param([string]$Spec)

    $parts = ([string]$Spec) -split "\|", 3
    if ($parts.Count -ne 3) {
        throw "StopCondition must use 'id|check_type|description': $Spec"
    }

    return [pscustomobject]@{
        id = $parts[0].Trim()
        check_type = $parts[1].Trim()
        description = $parts[2].Trim()
    }
}

function ConvertFrom-ApprovalRequirementSpec {
    param([string]$Spec)

    $parts = ([string]$Spec) -split "\|", 4
    if ($parts.Count -lt 3) {
        throw "ApprovalRequirement must use 'exact_action|required|reason|optional_approval_id': $Spec"
    }

    $required = $false
    if (![bool]::TryParse($parts[1].Trim(), [ref]$required)) {
        throw "ApprovalRequirement required value must be true or false: $Spec"
    }

    $record = [ordered]@{
        exact_action = $parts[0].Trim()
        required = $required
        reason = $parts[2].Trim()
    }

    if ($parts.Count -ge 4 -and ![string]::IsNullOrWhiteSpace($parts[3])) {
        $record.approval_id = $parts[3].Trim()
    }

    return [pscustomobject]$record
}

if ([string]::IsNullOrWhiteSpace($MissionId)) {
    $MissionId = "$(ConvertTo-AuthoringSlug -Value $ProjectId)-$(Get-Date -Format 'yyyyMMddHHmmss')"
}

$approvalRequirements = @($ApprovalRequirement | ForEach-Object { ConvertFrom-ApprovalRequirementSpec -Spec $_ })
$approvalGatedActions = @($approvalRequirements | Where-Object { [bool]$_.required } | ForEach-Object { ([string]$_.exact_action).Trim().ToLowerInvariant() })

if ($ForbiddenActions.Count -eq 0) {
    $ForbiddenActions = @($script:TsfKernelRestrictedActions | Where-Object { $approvalGatedActions -notcontains $_ })
}

$mission = [ordered]@{
    mission_id = $MissionId
    project_id = $ProjectId
    repo_path = $RepoPath
    lane = $Lane
    mission_type = $MissionType
    allowed_reads = @($AllowedReads)
    allowed_writes = @($AllowedWrites)
    forbidden_reads = @($ForbiddenReads)
    forbidden_writes = @($ForbiddenWrites)
    forbidden_actions = @($ForbiddenActions)
    expected_artifacts = @($ExpectedArtifacts)
    required_preflight_checks = @($RequiredPreflightChecks)
    required_postrun_checks = @($RequiredPostrunChecks)
    stop_conditions = @($StopCondition | ForEach-Object { ConvertFrom-StopConditionSpec -Spec $_ })
    approval_requirements = @($approvalRequirements)
    hq_escalation_policy = [ordered]@{
        default = $HqEscalationDefault
        escalate_on = @($HqEscalateOn)
        notes = $HqEscalationNotes
    }
    created_by = $CreatedBy
    created_at = (Get-Date).ToUniversalTime().ToString("o")
}

Write-TsfKernelJson -Value ([pscustomobject]$mission) -Path $OutFile

$shapeChecks = @()
if ($ValidateShape) {
    $parsedMission = Read-TsfKernelJson -Path $OutFile
    $shapeChecks += @(Test-TsfKernelMissionShape -Mission $parsedMission)
    $shapeChecks += @(Test-TsfKernelPathScope -Mission $parsedMission)
    $shapeChecks += @(Test-TsfKernelActionCoverage -Mission $parsedMission)
    $shapeChecks += @(Test-TsfKernelStopConditions -Mission $parsedMission)
}

$failedShapeChecks = @($shapeChecks | Where-Object { $_.status -eq "FAIL" })
$result = [pscustomobject]@{
    schema_version = 1
    generated_at = (Get-Date).ToString("o")
    mission_id = $MissionId
    out_file = (Get-TsfKernelFullPath -Path $OutFile)
    validates_shape = if ($ValidateShape) { ($failedShapeChecks.Count -eq 0) } else { $null }
    shape_check_failures = @($failedShapeChecks)
    executes_mission = $false
    starts_worker = $false
    starts_background_runner = $false
    mutates_product_repo = $false
}

$result | ConvertTo-Json -Depth 20
if ($failedShapeChecks.Count -gt 0) {
    exit 1
}

exit 0
